//
// Copyright (c) 2016 NVIDIA Corporation.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// Neither the name of the NVIDIA Corporation nor the names of its contributors
// may be used to endorse or promote products derived from this software
// without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARHSP_SHRD_SEM_H_INC_
#define ___ARHSP_SHRD_SEM_H_INC_

// Register HSP_SHRD_SEM_0_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SCR                       SS_0_REG_0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x4)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SCR                   SS_0_REG_0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x8)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SCR                   SS_0_REG_0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_1_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x10000)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SCR                       SS_1_REG_0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x10004)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SCR                   SS_1_REG_0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x10008)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SCR                   SS_1_REG_0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_2_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x20000)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SCR                       SS_2_REG_0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x20004)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SCR                   SS_2_REG_0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x20008)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SCR                   SS_2_REG_0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_3_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x30000)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SCR                       SS_3_REG_0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x30004)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SCR                   SS_3_REG_0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x30008)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SCR                   SS_3_REG_0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_4_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x40000)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SCR                       SS_4_REG_0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x40004)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SCR                   SS_4_REG_0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x40008)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SCR                   SS_4_REG_0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_5_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x50000)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SCR                       SS_5_REG_0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x50004)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SCR                   SS_5_REG_0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x50008)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SCR                   SS_5_REG_0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_6_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x60000)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SCR                       SS_6_REG_0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x60004)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SCR                   SS_6_REG_0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x60008)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SCR                   SS_6_REG_0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_7_SHRD_SMP_STA_0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0                   _MK_ADDR_CONST(0x70000)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SECURE                    0x0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SCR                       SS_7_REG_0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_WORD_COUNT                        0x1
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_SHIFT)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_RANGE                 31:0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_WOFFSET                       0x0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_0_SMP_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0                       _MK_ADDR_CONST(0x70004)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SECURE                        0x0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SCR                   SS_7_REG_0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_SHIFT)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_RANGE                 31:0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_WOFFSET                       0x0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0_SMP_SET_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0                       _MK_ADDR_CONST(0x70008)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SECURE                        0x0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SCR                   SS_7_REG_0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_WORD_COUNT                    0x1
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_RESET_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT                 _MK_SHIFT_CONST(0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_FIELD                 _MK_FIELD_CONST(0xffffffff, HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_SHIFT)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_RANGE                 31:0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_WOFFSET                       0x0
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT                       _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0_SMP_CLR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


//
// REGISTER LIST
//
#define LIST_ARHSP_SHRD_SEM_REGS(_op_) \
_op_(HSP_SHRD_SEM_0_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_0_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0) \
_op_(HSP_SHRD_SEM_1_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_1_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0) \
_op_(HSP_SHRD_SEM_2_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_2_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0) \
_op_(HSP_SHRD_SEM_3_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_3_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0) \
_op_(HSP_SHRD_SEM_4_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_4_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0) \
_op_(HSP_SHRD_SEM_5_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_5_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0) \
_op_(HSP_SHRD_SEM_6_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_6_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0) \
_op_(HSP_SHRD_SEM_7_SHRD_SMP_STA_0) \
_op_(HSP_SHRD_SEM_7_SHRD_SMP_STA_SET_0) \
_op_(HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0)


//
// ADDRESS SPACES
//

#define BASE_ADDRESS_HSP_SHRD   0x00000000

//
// ARHSP_SHRD_SEM REGISTER BANKS
//

#define HSP_SHRD0_FIRST_REG 0x0000 // HSP_SHRD_SEM_0_SHRD_SMP_STA_0
#define HSP_SHRD0_LAST_REG 0x0008 // HSP_SHRD_SEM_0_SHRD_SMP_STA_CLR_0
#define HSP_SHRD1_FIRST_REG 0x10000 // HSP_SHRD_SEM_1_SHRD_SMP_STA_0
#define HSP_SHRD1_LAST_REG 0x10008 // HSP_SHRD_SEM_1_SHRD_SMP_STA_CLR_0
#define HSP_SHRD2_FIRST_REG 0x20000 // HSP_SHRD_SEM_2_SHRD_SMP_STA_0
#define HSP_SHRD2_LAST_REG 0x20008 // HSP_SHRD_SEM_2_SHRD_SMP_STA_CLR_0
#define HSP_SHRD3_FIRST_REG 0x30000 // HSP_SHRD_SEM_3_SHRD_SMP_STA_0
#define HSP_SHRD3_LAST_REG 0x30008 // HSP_SHRD_SEM_3_SHRD_SMP_STA_CLR_0
#define HSP_SHRD4_FIRST_REG 0x40000 // HSP_SHRD_SEM_4_SHRD_SMP_STA_0
#define HSP_SHRD4_LAST_REG 0x40008 // HSP_SHRD_SEM_4_SHRD_SMP_STA_CLR_0
#define HSP_SHRD5_FIRST_REG 0x50000 // HSP_SHRD_SEM_5_SHRD_SMP_STA_0
#define HSP_SHRD5_LAST_REG 0x50008 // HSP_SHRD_SEM_5_SHRD_SMP_STA_CLR_0
#define HSP_SHRD6_FIRST_REG 0x60000 // HSP_SHRD_SEM_6_SHRD_SMP_STA_0
#define HSP_SHRD6_LAST_REG 0x60008 // HSP_SHRD_SEM_6_SHRD_SMP_STA_CLR_0
#define HSP_SHRD7_FIRST_REG 0x70000 // HSP_SHRD_SEM_7_SHRD_SMP_STA_0
#define HSP_SHRD7_LAST_REG 0x70008 // HSP_SHRD_SEM_7_SHRD_SMP_STA_CLR_0

// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARHSP_SHRD_SEM_H_INC_
