//
// Copyright (c) 2016 NVIDIA Corporation.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARRTC2_H_INC_
#define ___ARRTC2_H_INC_

// Register RTC2_RTCCR_0
#define RTC2_RTCCR_0                    _MK_ADDR_CONST(0x0)
#define RTC2_RTCCR_0_SECURE                     0x0
#define RTC2_RTCCR_0_SCR                        RTCSCR_0
#define RTC2_RTCCR_0_WORD_COUNT                         0x1
#define RTC2_RTCCR_0_RESET_VAL                  _MK_MASK_CONST(0x0)
#define RTC2_RTCCR_0_RESET_MASK                         _MK_MASK_CONST(0x1)
#define RTC2_RTCCR_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define RTC2_RTCCR_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define RTC2_RTCCR_0_READ_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_RTCCR_0_WRITE_MASK                         _MK_MASK_CONST(0x1)
#define RTC2_RTCCR_0_HDBG_SHIFT                 _MK_SHIFT_CONST(0)
#define RTC2_RTCCR_0_HDBG_FIELD                 _MK_FIELD_CONST(0x1, RTC2_RTCCR_0_HDBG_SHIFT)
#define RTC2_RTCCR_0_HDBG_RANGE                 0:0
#define RTC2_RTCCR_0_HDBG_WOFFSET                       0x0
#define RTC2_RTCCR_0_HDBG_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCCR_0_HDBG_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_RTCCR_0_HDBG_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCCR_0_HDBG_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register RTC2_RTCBR_0
#define RTC2_RTCBR_0                    _MK_ADDR_CONST(0x4)
#define RTC2_RTCBR_0_SECURE                     0x0
#define RTC2_RTCBR_0_SCR                        RTCSCR_0
#define RTC2_RTCBR_0_WORD_COUNT                         0x1
#define RTC2_RTCBR_0_RESET_VAL                  _MK_MASK_CONST(0x0)
#define RTC2_RTCBR_0_RESET_MASK                         _MK_MASK_CONST(0x1)
#define RTC2_RTCBR_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define RTC2_RTCBR_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define RTC2_RTCBR_0_READ_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_RTCBR_0_WRITE_MASK                         _MK_MASK_CONST(0x0)
#define RTC2_RTCBR_0_STATUS_SHIFT                       _MK_SHIFT_CONST(0)
#define RTC2_RTCBR_0_STATUS_FIELD                       _MK_FIELD_CONST(0x1, RTC2_RTCBR_0_STATUS_SHIFT)
#define RTC2_RTCBR_0_STATUS_RANGE                       0:0
#define RTC2_RTCBR_0_STATUS_WOFFSET                     0x0
#define RTC2_RTCBR_0_STATUS_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCBR_0_STATUS_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_RTCBR_0_STATUS_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_RTCBR_0_STATUS_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register RTC2_RTCSCR_0
#define RTC2_RTCSCR_0                   _MK_ADDR_CONST(0x8)
#define RTC2_RTCSCR_0_SECURE                    0x0
#define RTC2_RTCSCR_0_SCR                       RTCSCR_0
#define RTC2_RTCSCR_0_WORD_COUNT                        0x1
#define RTC2_RTCSCR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_RTCSCR_0_RESET_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSCR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCSCR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSCR_0_READ_MASK                         _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSCR_0_WRITE_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSCR_0_CNT_SHIFT                 _MK_SHIFT_CONST(0)
#define RTC2_RTCSCR_0_CNT_FIELD                 _MK_FIELD_CONST(0xffffffff, RTC2_RTCSCR_0_CNT_SHIFT)
#define RTC2_RTCSCR_0_CNT_RANGE                 31:0
#define RTC2_RTCSCR_0_CNT_WOFFSET                       0x0
#define RTC2_RTCSCR_0_CNT_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCSCR_0_CNT_DEFAULT_MASK                  _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSCR_0_CNT_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCSCR_0_CNT_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register RTC2_RTCSSCR_0
#define RTC2_RTCSSCR_0                  _MK_ADDR_CONST(0xc)
#define RTC2_RTCSSCR_0_SECURE                   0x0
#define RTC2_RTCSSCR_0_SCR                      RTCSCR_0
#define RTC2_RTCSSCR_0_WORD_COUNT                       0x1
#define RTC2_RTCSSCR_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define RTC2_RTCSSCR_0_RESET_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSSCR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSSCR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_RTCSSCR_0_READ_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSSCR_0_WRITE_MASK                       _MK_MASK_CONST(0x0)
#define RTC2_RTCSSCR_0_CNT_SHIFT                        _MK_SHIFT_CONST(0)
#define RTC2_RTCSSCR_0_CNT_FIELD                        _MK_FIELD_CONST(0xffffffff, RTC2_RTCSSCR_0_CNT_SHIFT)
#define RTC2_RTCSSCR_0_CNT_RANGE                        31:0
#define RTC2_RTCSSCR_0_CNT_WOFFSET                      0x0
#define RTC2_RTCSSCR_0_CNT_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_RTCSSCR_0_CNT_DEFAULT_MASK                 _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSSCR_0_CNT_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSSCR_0_CNT_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)


// Register RTC2_RTCMCR_0
#define RTC2_RTCMCR_0                   _MK_ADDR_CONST(0x10)
#define RTC2_RTCMCR_0_SECURE                    0x0
#define RTC2_RTCMCR_0_SCR                       RTCSCR_0
#define RTC2_RTCMCR_0_WORD_COUNT                        0x1
#define RTC2_RTCMCR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_RTCMCR_0_RESET_MASK                        _MK_MASK_CONST(0x3ff)
#define RTC2_RTCMCR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCMCR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCMCR_0_READ_MASK                         _MK_MASK_CONST(0x3ff)
#define RTC2_RTCMCR_0_WRITE_MASK                        _MK_MASK_CONST(0x0)
#define RTC2_RTCMCR_0_CNT_SHIFT                 _MK_SHIFT_CONST(0)
#define RTC2_RTCMCR_0_CNT_FIELD                 _MK_FIELD_CONST(0x3ff, RTC2_RTCMCR_0_CNT_SHIFT)
#define RTC2_RTCMCR_0_CNT_RANGE                 9:0
#define RTC2_RTCMCR_0_CNT_WOFFSET                       0x0
#define RTC2_RTCMCR_0_CNT_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCMCR_0_CNT_DEFAULT_MASK                  _MK_MASK_CONST(0x3ff)
#define RTC2_RTCMCR_0_CNT_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCMCR_0_CNT_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register RTC2_RTCSAR0_0
#define RTC2_RTCSAR0_0                  _MK_ADDR_CONST(0x14)
#define RTC2_RTCSAR0_0_SECURE                   0x0
#define RTC2_RTCSAR0_0_SCR                      RTCSCR_0
#define RTC2_RTCSAR0_0_WORD_COUNT                       0x1
#define RTC2_RTCSAR0_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR0_0_RESET_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR0_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR0_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR0_0_READ_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR0_0_WRITE_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR0_0_VALUE_SHIFT                      _MK_SHIFT_CONST(0)
#define RTC2_RTCSAR0_0_VALUE_FIELD                      _MK_FIELD_CONST(0xffffffff, RTC2_RTCSAR0_0_VALUE_SHIFT)
#define RTC2_RTCSAR0_0_VALUE_RANGE                      31:0
#define RTC2_RTCSAR0_0_VALUE_WOFFSET                    0x0
#define RTC2_RTCSAR0_0_VALUE_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR0_0_VALUE_DEFAULT_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR0_0_VALUE_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR0_0_VALUE_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register RTC2_RTCSAR1_0
#define RTC2_RTCSAR1_0                  _MK_ADDR_CONST(0x18)
#define RTC2_RTCSAR1_0_SECURE                   0x0
#define RTC2_RTCSAR1_0_SCR                      RTCSCR_0
#define RTC2_RTCSAR1_0_WORD_COUNT                       0x1
#define RTC2_RTCSAR1_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR1_0_RESET_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR1_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR1_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR1_0_READ_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR1_0_WRITE_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR1_0_VALUE_SHIFT                      _MK_SHIFT_CONST(0)
#define RTC2_RTCSAR1_0_VALUE_FIELD                      _MK_FIELD_CONST(0xffffffff, RTC2_RTCSAR1_0_VALUE_SHIFT)
#define RTC2_RTCSAR1_0_VALUE_RANGE                      31:0
#define RTC2_RTCSAR1_0_VALUE_WOFFSET                    0x0
#define RTC2_RTCSAR1_0_VALUE_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR1_0_VALUE_DEFAULT_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSAR1_0_VALUE_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCSAR1_0_VALUE_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register RTC2_RTCMAR_0
#define RTC2_RTCMAR_0                   _MK_ADDR_CONST(0x1c)
#define RTC2_RTCMAR_0_SECURE                    0x0
#define RTC2_RTCMAR_0_SCR                       RTCSCR_0
#define RTC2_RTCMAR_0_WORD_COUNT                        0x1
#define RTC2_RTCMAR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_RTCMAR_0_RESET_MASK                        _MK_MASK_CONST(0x3ff)
#define RTC2_RTCMAR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCMAR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCMAR_0_READ_MASK                         _MK_MASK_CONST(0x3ff)
#define RTC2_RTCMAR_0_WRITE_MASK                        _MK_MASK_CONST(0x3ff)
#define RTC2_RTCMAR_0_VALUE_SHIFT                       _MK_SHIFT_CONST(0)
#define RTC2_RTCMAR_0_VALUE_FIELD                       _MK_FIELD_CONST(0x3ff, RTC2_RTCMAR_0_VALUE_SHIFT)
#define RTC2_RTCMAR_0_VALUE_RANGE                       9:0
#define RTC2_RTCMAR_0_VALUE_WOFFSET                     0x0
#define RTC2_RTCMAR_0_VALUE_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCMAR_0_VALUE_DEFAULT_MASK                        _MK_MASK_CONST(0x3ff)
#define RTC2_RTCMAR_0_VALUE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_RTCMAR_0_VALUE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register RTC2_RTCSCAR_0
#define RTC2_RTCSCAR_0                  _MK_ADDR_CONST(0x20)
#define RTC2_RTCSCAR_0_SECURE                   0x0
#define RTC2_RTCSCAR_0_SCR                      RTCSCR_0
#define RTC2_RTCSCAR_0_WORD_COUNT                       0x1
#define RTC2_RTCSCAR_0_RESET_VAL                        _MK_MASK_CONST(0x40000000)
#define RTC2_RTCSCAR_0_RESET_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSCAR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSCAR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_RTCSCAR_0_READ_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSCAR_0_WRITE_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCSCAR_0_PTV_SHIFT                        _MK_SHIFT_CONST(0)
#define RTC2_RTCSCAR_0_PTV_FIELD                        _MK_FIELD_CONST(0x3fffffff, RTC2_RTCSCAR_0_PTV_SHIFT)
#define RTC2_RTCSCAR_0_PTV_RANGE                        29:0
#define RTC2_RTCSCAR_0_PTV_WOFFSET                      0x0
#define RTC2_RTCSCAR_0_PTV_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_RTCSCAR_0_PTV_DEFAULT_MASK                 _MK_MASK_CONST(0x3fffffff)
#define RTC2_RTCSCAR_0_PTV_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSCAR_0_PTV_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define RTC2_RTCSCAR_0_PER_SHIFT                        _MK_SHIFT_CONST(30)
#define RTC2_RTCSCAR_0_PER_FIELD                        _MK_FIELD_CONST(0x1, RTC2_RTCSCAR_0_PER_SHIFT)
#define RTC2_RTCSCAR_0_PER_RANGE                        30:30
#define RTC2_RTCSCAR_0_PER_WOFFSET                      0x0
#define RTC2_RTCSCAR_0_PER_DEFAULT                      _MK_MASK_CONST(0x1)
#define RTC2_RTCSCAR_0_PER_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define RTC2_RTCSCAR_0_PER_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_RTCSCAR_0_PER_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define RTC2_RTCSCAR_0_EN_SHIFT                 _MK_SHIFT_CONST(31)
#define RTC2_RTCSCAR_0_EN_FIELD                 _MK_FIELD_CONST(0x1, RTC2_RTCSCAR_0_EN_SHIFT)
#define RTC2_RTCSCAR_0_EN_RANGE                 31:31
#define RTC2_RTCSCAR_0_EN_WOFFSET                       0x0
#define RTC2_RTCSCAR_0_EN_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCSCAR_0_EN_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_RTCSCAR_0_EN_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCSCAR_0_EN_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register RTC2_RTCMCAR_0
#define RTC2_RTCMCAR_0                  _MK_ADDR_CONST(0x24)
#define RTC2_RTCMCAR_0_SECURE                   0x0
#define RTC2_RTCMCAR_0_SCR                      RTCSCR_0
#define RTC2_RTCMCAR_0_WORD_COUNT                       0x1
#define RTC2_RTCMCAR_0_RESET_VAL                        _MK_MASK_CONST(0x40000000)
#define RTC2_RTCMCAR_0_RESET_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCMCAR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_RTCMCAR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_RTCMCAR_0_READ_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCMCAR_0_WRITE_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCMCAR_0_PTV_SHIFT                        _MK_SHIFT_CONST(0)
#define RTC2_RTCMCAR_0_PTV_FIELD                        _MK_FIELD_CONST(0x3fffffff, RTC2_RTCMCAR_0_PTV_SHIFT)
#define RTC2_RTCMCAR_0_PTV_RANGE                        29:0
#define RTC2_RTCMCAR_0_PTV_WOFFSET                      0x0
#define RTC2_RTCMCAR_0_PTV_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_RTCMCAR_0_PTV_DEFAULT_MASK                 _MK_MASK_CONST(0x3fffffff)
#define RTC2_RTCMCAR_0_PTV_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_RTCMCAR_0_PTV_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define RTC2_RTCMCAR_0_PER_SHIFT                        _MK_SHIFT_CONST(30)
#define RTC2_RTCMCAR_0_PER_FIELD                        _MK_FIELD_CONST(0x1, RTC2_RTCMCAR_0_PER_SHIFT)
#define RTC2_RTCMCAR_0_PER_RANGE                        30:30
#define RTC2_RTCMCAR_0_PER_WOFFSET                      0x0
#define RTC2_RTCMCAR_0_PER_DEFAULT                      _MK_MASK_CONST(0x1)
#define RTC2_RTCMCAR_0_PER_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define RTC2_RTCMCAR_0_PER_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_RTCMCAR_0_PER_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define RTC2_RTCMCAR_0_EN_SHIFT                 _MK_SHIFT_CONST(31)
#define RTC2_RTCMCAR_0_EN_FIELD                 _MK_FIELD_CONST(0x1, RTC2_RTCMCAR_0_EN_SHIFT)
#define RTC2_RTCMCAR_0_EN_RANGE                 31:31
#define RTC2_RTCMCAR_0_EN_WOFFSET                       0x0
#define RTC2_RTCMCAR_0_EN_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCMCAR_0_EN_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_RTCMCAR_0_EN_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCMCAR_0_EN_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register RTC2_RTCIER_0
#define RTC2_RTCIER_0                   _MK_ADDR_CONST(0x28)
#define RTC2_RTCIER_0_SECURE                    0x0
#define RTC2_RTCIER_0_SCR                       RTCSCR_0
#define RTC2_RTCIER_0_WORD_COUNT                        0x1
#define RTC2_RTCIER_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_RESET_MASK                        _MK_MASK_CONST(0x1f)
#define RTC2_RTCIER_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_READ_MASK                         _MK_MASK_CONST(0x1f)
#define RTC2_RTCIER_0_WRITE_MASK                        _MK_MASK_CONST(0x1f)
#define RTC2_RTCIER_0_SEC_ALARM_SHIFT                   _MK_SHIFT_CONST(0)
#define RTC2_RTCIER_0_SEC_ALARM_FIELD                   _MK_FIELD_CONST(0x3, RTC2_RTCIER_0_SEC_ALARM_SHIFT)
#define RTC2_RTCIER_0_SEC_ALARM_RANGE                   1:0
#define RTC2_RTCIER_0_SEC_ALARM_WOFFSET                 0x0
#define RTC2_RTCIER_0_SEC_ALARM_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_SEC_ALARM_DEFAULT_MASK                    _MK_MASK_CONST(0x3)
#define RTC2_RTCIER_0_SEC_ALARM_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_SEC_ALARM_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define RTC2_RTCIER_0_MSEC_ALARM_SHIFT                  _MK_SHIFT_CONST(2)
#define RTC2_RTCIER_0_MSEC_ALARM_FIELD                  _MK_FIELD_CONST(0x1, RTC2_RTCIER_0_MSEC_ALARM_SHIFT)
#define RTC2_RTCIER_0_MSEC_ALARM_RANGE                  2:2
#define RTC2_RTCIER_0_MSEC_ALARM_WOFFSET                        0x0
#define RTC2_RTCIER_0_MSEC_ALARM_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_MSEC_ALARM_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define RTC2_RTCIER_0_MSEC_ALARM_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_MSEC_ALARM_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define RTC2_RTCIER_0_SEC_CDN_ALARM_SHIFT                       _MK_SHIFT_CONST(3)
#define RTC2_RTCIER_0_SEC_CDN_ALARM_FIELD                       _MK_FIELD_CONST(0x1, RTC2_RTCIER_0_SEC_CDN_ALARM_SHIFT)
#define RTC2_RTCIER_0_SEC_CDN_ALARM_RANGE                       3:3
#define RTC2_RTCIER_0_SEC_CDN_ALARM_WOFFSET                     0x0
#define RTC2_RTCIER_0_SEC_CDN_ALARM_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_SEC_CDN_ALARM_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_RTCIER_0_SEC_CDN_ALARM_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_SEC_CDN_ALARM_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_RTCIER_0_MSEC_CDN_ALARM_SHIFT                      _MK_SHIFT_CONST(4)
#define RTC2_RTCIER_0_MSEC_CDN_ALARM_FIELD                      _MK_FIELD_CONST(0x1, RTC2_RTCIER_0_MSEC_CDN_ALARM_SHIFT)
#define RTC2_RTCIER_0_MSEC_CDN_ALARM_RANGE                      4:4
#define RTC2_RTCIER_0_MSEC_CDN_ALARM_WOFFSET                    0x0
#define RTC2_RTCIER_0_MSEC_CDN_ALARM_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_MSEC_CDN_ALARM_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define RTC2_RTCIER_0_MSEC_CDN_ALARM_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCIER_0_MSEC_CDN_ALARM_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register RTC2_RTCISR_0
#define RTC2_RTCISR_0                   _MK_ADDR_CONST(0x2c)
#define RTC2_RTCISR_0_SECURE                    0x0
#define RTC2_RTCISR_0_SCR                       RTCSCR_0
#define RTC2_RTCISR_0_WORD_COUNT                        0x1
#define RTC2_RTCISR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_RESET_MASK                        _MK_MASK_CONST(0x1f)
#define RTC2_RTCISR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_READ_MASK                         _MK_MASK_CONST(0x1f)
#define RTC2_RTCISR_0_WRITE_MASK                        _MK_MASK_CONST(0x1f)
#define RTC2_RTCISR_0_SEC_ALARM_SHIFT                   _MK_SHIFT_CONST(0)
#define RTC2_RTCISR_0_SEC_ALARM_FIELD                   _MK_FIELD_CONST(0x3, RTC2_RTCISR_0_SEC_ALARM_SHIFT)
#define RTC2_RTCISR_0_SEC_ALARM_RANGE                   1:0
#define RTC2_RTCISR_0_SEC_ALARM_WOFFSET                 0x0
#define RTC2_RTCISR_0_SEC_ALARM_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_SEC_ALARM_DEFAULT_MASK                    _MK_MASK_CONST(0x3)
#define RTC2_RTCISR_0_SEC_ALARM_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_SEC_ALARM_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define RTC2_RTCISR_0_MSEC_ALARM_SHIFT                  _MK_SHIFT_CONST(2)
#define RTC2_RTCISR_0_MSEC_ALARM_FIELD                  _MK_FIELD_CONST(0x1, RTC2_RTCISR_0_MSEC_ALARM_SHIFT)
#define RTC2_RTCISR_0_MSEC_ALARM_RANGE                  2:2
#define RTC2_RTCISR_0_MSEC_ALARM_WOFFSET                        0x0
#define RTC2_RTCISR_0_MSEC_ALARM_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_MSEC_ALARM_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define RTC2_RTCISR_0_MSEC_ALARM_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_MSEC_ALARM_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define RTC2_RTCISR_0_SEC_CDN_ALARM_SHIFT                       _MK_SHIFT_CONST(3)
#define RTC2_RTCISR_0_SEC_CDN_ALARM_FIELD                       _MK_FIELD_CONST(0x1, RTC2_RTCISR_0_SEC_CDN_ALARM_SHIFT)
#define RTC2_RTCISR_0_SEC_CDN_ALARM_RANGE                       3:3
#define RTC2_RTCISR_0_SEC_CDN_ALARM_WOFFSET                     0x0
#define RTC2_RTCISR_0_SEC_CDN_ALARM_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_SEC_CDN_ALARM_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_RTCISR_0_SEC_CDN_ALARM_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_SEC_CDN_ALARM_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_RTCISR_0_MSEC_CDN_ALARM_SHIFT                      _MK_SHIFT_CONST(4)
#define RTC2_RTCISR_0_MSEC_CDN_ALARM_FIELD                      _MK_FIELD_CONST(0x1, RTC2_RTCISR_0_MSEC_CDN_ALARM_SHIFT)
#define RTC2_RTCISR_0_MSEC_CDN_ALARM_RANGE                      4:4
#define RTC2_RTCISR_0_MSEC_CDN_ALARM_WOFFSET                    0x0
#define RTC2_RTCISR_0_MSEC_CDN_ALARM_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_MSEC_CDN_ALARM_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define RTC2_RTCISR_0_MSEC_CDN_ALARM_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCISR_0_MSEC_CDN_ALARM_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register RTC2_RTCIVR_0
#define RTC2_RTCIVR_0                   _MK_ADDR_CONST(0x30)
#define RTC2_RTCIVR_0_SECURE                    0x0
#define RTC2_RTCIVR_0_SCR                       RTCSCR_0
#define RTC2_RTCIVR_0_WORD_COUNT                        0x1
#define RTC2_RTCIVR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_RESET_MASK                        _MK_MASK_CONST(0x1f)
#define RTC2_RTCIVR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_READ_MASK                         _MK_MASK_CONST(0x1f)
#define RTC2_RTCIVR_0_WRITE_MASK                        _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_SEC_ALARM_SHIFT                   _MK_SHIFT_CONST(0)
#define RTC2_RTCIVR_0_SEC_ALARM_FIELD                   _MK_FIELD_CONST(0x3, RTC2_RTCIVR_0_SEC_ALARM_SHIFT)
#define RTC2_RTCIVR_0_SEC_ALARM_RANGE                   1:0
#define RTC2_RTCIVR_0_SEC_ALARM_WOFFSET                 0x0
#define RTC2_RTCIVR_0_SEC_ALARM_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_SEC_ALARM_DEFAULT_MASK                    _MK_MASK_CONST(0x3)
#define RTC2_RTCIVR_0_SEC_ALARM_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_SEC_ALARM_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define RTC2_RTCIVR_0_MSEC_ALARM_SHIFT                  _MK_SHIFT_CONST(2)
#define RTC2_RTCIVR_0_MSEC_ALARM_FIELD                  _MK_FIELD_CONST(0x1, RTC2_RTCIVR_0_MSEC_ALARM_SHIFT)
#define RTC2_RTCIVR_0_MSEC_ALARM_RANGE                  2:2
#define RTC2_RTCIVR_0_MSEC_ALARM_WOFFSET                        0x0
#define RTC2_RTCIVR_0_MSEC_ALARM_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_MSEC_ALARM_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define RTC2_RTCIVR_0_MSEC_ALARM_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_MSEC_ALARM_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define RTC2_RTCIVR_0_SEC_CDN_ALARM_SHIFT                       _MK_SHIFT_CONST(3)
#define RTC2_RTCIVR_0_SEC_CDN_ALARM_FIELD                       _MK_FIELD_CONST(0x1, RTC2_RTCIVR_0_SEC_CDN_ALARM_SHIFT)
#define RTC2_RTCIVR_0_SEC_CDN_ALARM_RANGE                       3:3
#define RTC2_RTCIVR_0_SEC_CDN_ALARM_WOFFSET                     0x0
#define RTC2_RTCIVR_0_SEC_CDN_ALARM_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_SEC_CDN_ALARM_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_RTCIVR_0_SEC_CDN_ALARM_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_SEC_CDN_ALARM_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_SHIFT                      _MK_SHIFT_CONST(4)
#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_FIELD                      _MK_FIELD_CONST(0x1, RTC2_RTCIVR_0_MSEC_CDN_ALARM_SHIFT)
#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_RANGE                      4:4
#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_WOFFSET                    0x0
#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCIVR_0_MSEC_CDN_ALARM_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register RTC2_RTCFIR_0
#define RTC2_RTCFIR_0                   _MK_ADDR_CONST(0x34)
#define RTC2_RTCFIR_0_SECURE                    0x0
#define RTC2_RTCFIR_0_SCR                       RTCSCR_0
#define RTC2_RTCFIR_0_WORD_COUNT                        0x1
#define RTC2_RTCFIR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_RESET_MASK                        _MK_MASK_CONST(0x1f)
#define RTC2_RTCFIR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_READ_MASK                         _MK_MASK_CONST(0x1f)
#define RTC2_RTCFIR_0_WRITE_MASK                        _MK_MASK_CONST(0x1f)
#define RTC2_RTCFIR_0_SEC_ALARM_SHIFT                   _MK_SHIFT_CONST(0)
#define RTC2_RTCFIR_0_SEC_ALARM_FIELD                   _MK_FIELD_CONST(0x3, RTC2_RTCFIR_0_SEC_ALARM_SHIFT)
#define RTC2_RTCFIR_0_SEC_ALARM_RANGE                   1:0
#define RTC2_RTCFIR_0_SEC_ALARM_WOFFSET                 0x0
#define RTC2_RTCFIR_0_SEC_ALARM_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_SEC_ALARM_DEFAULT_MASK                    _MK_MASK_CONST(0x3)
#define RTC2_RTCFIR_0_SEC_ALARM_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_SEC_ALARM_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define RTC2_RTCFIR_0_MSEC_ALARM_SHIFT                  _MK_SHIFT_CONST(2)
#define RTC2_RTCFIR_0_MSEC_ALARM_FIELD                  _MK_FIELD_CONST(0x1, RTC2_RTCFIR_0_MSEC_ALARM_SHIFT)
#define RTC2_RTCFIR_0_MSEC_ALARM_RANGE                  2:2
#define RTC2_RTCFIR_0_MSEC_ALARM_WOFFSET                        0x0
#define RTC2_RTCFIR_0_MSEC_ALARM_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_MSEC_ALARM_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define RTC2_RTCFIR_0_MSEC_ALARM_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_MSEC_ALARM_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define RTC2_RTCFIR_0_SEC_CDN_ALARM_SHIFT                       _MK_SHIFT_CONST(3)
#define RTC2_RTCFIR_0_SEC_CDN_ALARM_FIELD                       _MK_FIELD_CONST(0x1, RTC2_RTCFIR_0_SEC_CDN_ALARM_SHIFT)
#define RTC2_RTCFIR_0_SEC_CDN_ALARM_RANGE                       3:3
#define RTC2_RTCFIR_0_SEC_CDN_ALARM_WOFFSET                     0x0
#define RTC2_RTCFIR_0_SEC_CDN_ALARM_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_SEC_CDN_ALARM_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_RTCFIR_0_SEC_CDN_ALARM_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_SEC_CDN_ALARM_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_SHIFT                      _MK_SHIFT_CONST(4)
#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_FIELD                      _MK_FIELD_CONST(0x1, RTC2_RTCFIR_0_MSEC_CDN_ALARM_SHIFT)
#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_RANGE                      4:4
#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_WOFFSET                    0x0
#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_DEFAULT_MASK                       _MK_MASK_CONST(0x1)
#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_RTCFIR_0_MSEC_CDN_ALARM_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register RTC2_RTCRSR_0
#define RTC2_RTCRSR_0                   _MK_ADDR_CONST(0x38)
#define RTC2_RTCRSR_0_SECURE                    0x0
#define RTC2_RTCRSR_0_SCR                       RTCSCR_0
#define RTC2_RTCRSR_0_WORD_COUNT                        0x1
#define RTC2_RTCRSR_0_RESET_VAL                         _MK_MASK_CONST(0x1)
#define RTC2_RTCRSR_0_RESET_MASK                        _MK_MASK_CONST(0x31)
#define RTC2_RTCRSR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define RTC2_RTCRSR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_RTCRSR_0_READ_MASK                         _MK_MASK_CONST(0x31)
#define RTC2_RTCRSR_0_WRITE_MASK                        _MK_MASK_CONST(0x31)
#define RTC2_RTCRSR_0_FR_SHIFT                  _MK_SHIFT_CONST(0)
#define RTC2_RTCRSR_0_FR_FIELD                  _MK_FIELD_CONST(0x1, RTC2_RTCRSR_0_FR_SHIFT)
#define RTC2_RTCRSR_0_FR_RANGE                  0:0
#define RTC2_RTCRSR_0_FR_WOFFSET                        0x0
#define RTC2_RTCRSR_0_FR_DEFAULT                        _MK_MASK_CONST(0x1)
#define RTC2_RTCRSR_0_FR_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define RTC2_RTCRSR_0_FR_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_RTCRSR_0_FR_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define RTC2_RTCRSR_0_MBS_SHIFT                 _MK_SHIFT_CONST(4)
#define RTC2_RTCRSR_0_MBS_FIELD                 _MK_FIELD_CONST(0x3, RTC2_RTCRSR_0_MBS_SHIFT)
#define RTC2_RTCRSR_0_MBS_RANGE                 5:4
#define RTC2_RTCRSR_0_MBS_WOFFSET                       0x0
#define RTC2_RTCRSR_0_MBS_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCRSR_0_MBS_DEFAULT_MASK                  _MK_MASK_CONST(0x3)
#define RTC2_RTCRSR_0_MBS_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_RTCRSR_0_MBS_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register RTC2_RTCDR_0
#define RTC2_RTCDR_0                    _MK_ADDR_CONST(0x3c)
#define RTC2_RTCDR_0_SECURE                     0x0
#define RTC2_RTCDR_0_SCR                        RTCSCR_0
#define RTC2_RTCDR_0_WORD_COUNT                         0x1
#define RTC2_RTCDR_0_RESET_VAL                  _MK_MASK_CONST(0xfff007c)
#define RTC2_RTCDR_0_RESET_MASK                         _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCDR_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define RTC2_RTCDR_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define RTC2_RTCDR_0_READ_MASK                  _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCDR_0_WRITE_MASK                         _MK_MASK_CONST(0xffffffff)
#define RTC2_RTCDR_0_N_SHIFT                    _MK_SHIFT_CONST(0)
#define RTC2_RTCDR_0_N_FIELD                    _MK_FIELD_CONST(0xffff, RTC2_RTCDR_0_N_SHIFT)
#define RTC2_RTCDR_0_N_RANGE                    15:0
#define RTC2_RTCDR_0_N_WOFFSET                  0x0
#define RTC2_RTCDR_0_N_DEFAULT                  _MK_MASK_CONST(0x7c)
#define RTC2_RTCDR_0_N_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define RTC2_RTCDR_0_N_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCDR_0_N_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define RTC2_RTCDR_0_D_SHIFT                    _MK_SHIFT_CONST(16)
#define RTC2_RTCDR_0_D_FIELD                    _MK_FIELD_CONST(0xffff, RTC2_RTCDR_0_D_SHIFT)
#define RTC2_RTCDR_0_D_RANGE                    31:16
#define RTC2_RTCDR_0_D_WOFFSET                  0x0
#define RTC2_RTCDR_0_D_DEFAULT                  _MK_MASK_CONST(0xfff)
#define RTC2_RTCDR_0_D_DEFAULT_MASK                     _MK_MASK_CONST(0xffff)
#define RTC2_RTCDR_0_D_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_RTCDR_0_D_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register RTC2_AOWDTCR_0
#define RTC2_AOWDTCR_0                  _MK_ADDR_CONST(0x100)
#define RTC2_AOWDTCR_0_SECURE                   0x0
#define RTC2_AOWDTCR_0_SCR                      AOWDTSCR_0
#define RTC2_AOWDTCR_0_WORD_COUNT                       0x1
#define RTC2_AOWDTCR_0_RESET_VAL                        _MK_MASK_CONST(0x700000)
#define RTC2_AOWDTCR_0_RESET_MASK                       _MK_MASK_CONST(0xf07fffff)
#define RTC2_AOWDTCR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_READ_MASK                        _MK_MASK_CONST(0xf07fffff)
#define RTC2_AOWDTCR_0_WRITE_MASK                       _MK_MASK_CONST(0xf07fffff)
#define RTC2_AOWDTCR_0_TIMERSOURCE_SHIFT                        _MK_SHIFT_CONST(0)
#define RTC2_AOWDTCR_0_TIMERSOURCE_FIELD                        _MK_FIELD_CONST(0xf, RTC2_AOWDTCR_0_TIMERSOURCE_SHIFT)
#define RTC2_AOWDTCR_0_TIMERSOURCE_RANGE                        3:0
#define RTC2_AOWDTCR_0_TIMERSOURCE_WOFFSET                      0x0
#define RTC2_AOWDTCR_0_TIMERSOURCE_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_TIMERSOURCE_DEFAULT_MASK                 _MK_MASK_CONST(0xf)
#define RTC2_AOWDTCR_0_TIMERSOURCE_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_TIMERSOURCE_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_PERIOD_SHIFT                     _MK_SHIFT_CONST(4)
#define RTC2_AOWDTCR_0_PERIOD_FIELD                     _MK_FIELD_CONST(0xff, RTC2_AOWDTCR_0_PERIOD_SHIFT)
#define RTC2_AOWDTCR_0_PERIOD_RANGE                     11:4
#define RTC2_AOWDTCR_0_PERIOD_WOFFSET                   0x0
#define RTC2_AOWDTCR_0_PERIOD_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_PERIOD_DEFAULT_MASK                      _MK_MASK_CONST(0xff)
#define RTC2_AOWDTCR_0_PERIOD_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_PERIOD_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_SHIFT                       _MK_SHIFT_CONST(12)
#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_FIELD                       _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_SHIFT)
#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_RANGE                       12:12
#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_WOFFSET                     0x0
#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_LOCALINTERRUPTENABLE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_WAKEENABLE_SHIFT                 _MK_SHIFT_CONST(13)
#define RTC2_AOWDTCR_0_WAKEENABLE_FIELD                 _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_WAKEENABLE_SHIFT)
#define RTC2_AOWDTCR_0_WAKEENABLE_RANGE                 13:13
#define RTC2_AOWDTCR_0_WAKEENABLE_WOFFSET                       0x0
#define RTC2_AOWDTCR_0_WAKEENABLE_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WAKEENABLE_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_WAKEENABLE_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WAKEENABLE_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_WAKECOLDENABLE_SHIFT                     _MK_SHIFT_CONST(14)
#define RTC2_AOWDTCR_0_WAKECOLDENABLE_FIELD                     _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_WAKECOLDENABLE_SHIFT)
#define RTC2_AOWDTCR_0_WAKECOLDENABLE_RANGE                     14:14
#define RTC2_AOWDTCR_0_WAKECOLDENABLE_WOFFSET                   0x0
#define RTC2_AOWDTCR_0_WAKECOLDENABLE_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WAKECOLDENABLE_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_WAKECOLDENABLE_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WAKECOLDENABLE_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_SHIFT                     _MK_SHIFT_CONST(15)
#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_FIELD                     _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_SHIFT)
#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_RANGE                     15:15
#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_WOFFSET                   0x0
#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_SYSTEMDEBUGRESETENABLE_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_SHIFT                       _MK_SHIFT_CONST(16)
#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_FIELD                       _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_SHIFT)
#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_RANGE                       16:16
#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_WOFFSET                     0x0
#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_SYSTEMPORRESETENABLE_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_SHIFT                    _MK_SHIFT_CONST(17)
#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_FIELD                    _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_SHIFT)
#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_RANGE                    17:17
#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_WOFFSET                  0x0
#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_DEFAULT_MASK                     _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WINDOWEDOPERATIONENABLE_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_SHIFT                    _MK_SHIFT_CONST(18)
#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_FIELD                    _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_SHIFT)
#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_RANGE                    18:18
#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_WOFFSET                  0x0
#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_DEFAULT_MASK                     _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_CHALLENGERESPONSEENABLE_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_SHIFT                 _MK_SHIFT_CONST(19)
#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_FIELD                 _MK_FIELD_CONST(0x1, RTC2_AOWDTCR_0_TSCREFERENCEENABLE_SHIFT)
#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_RANGE                 19:19
#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_WOFFSET                       0x0
#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_TSCREFERENCEENABLE_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_SHIFT                     _MK_SHIFT_CONST(20)
#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_FIELD                     _MK_FIELD_CONST(0x7, RTC2_AOWDTCR_0_ERRORTHRESHOLD_SHIFT)
#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_RANGE                     22:20
#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_WOFFSET                   0x0
#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_DEFAULT                   _MK_MASK_CONST(0x7)
#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_DEFAULT_MASK                      _MK_MASK_CONST(0x7)
#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_ERRORTHRESHOLD_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_SHIFT                  _MK_SHIFT_CONST(28)
#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_FIELD                  _MK_FIELD_CONST(0xf, RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_SHIFT)
#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_RANGE                  31:28
#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_WOFFSET                        0x0
#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_DEFAULT_MASK                   _MK_MASK_CONST(0xf)
#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCR_0_WINDOWEDRESTARTDISABLEMAP_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)


// Register RTC2_AOWDTSR_0
#define RTC2_AOWDTSR_0                  _MK_ADDR_CONST(0x104)
#define RTC2_AOWDTSR_0_SECURE                   0x0
#define RTC2_AOWDTSR_0_SCR                      AOWDTSCR_0
#define RTC2_AOWDTSR_0_WORD_COUNT                       0x1
#define RTC2_AOWDTSR_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_RESET_MASK                       _MK_MASK_CONST(0x17fff)
#define RTC2_AOWDTSR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_READ_MASK                        _MK_MASK_CONST(0x17fff)
#define RTC2_AOWDTSR_0_WRITE_MASK                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_ENABLED_SHIFT                    _MK_SHIFT_CONST(0)
#define RTC2_AOWDTSR_0_ENABLED_FIELD                    _MK_FIELD_CONST(0x1, RTC2_AOWDTSR_0_ENABLED_SHIFT)
#define RTC2_AOWDTSR_0_ENABLED_RANGE                    0:0
#define RTC2_AOWDTSR_0_ENABLED_WOFFSET                  0x0
#define RTC2_AOWDTSR_0_ENABLED_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_ENABLED_DEFAULT_MASK                     _MK_MASK_CONST(0x1)
#define RTC2_AOWDTSR_0_ENABLED_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_ENABLED_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_SHIFT                       _MK_SHIFT_CONST(1)
#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_FIELD                       _MK_FIELD_CONST(0x1, RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_SHIFT)
#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_RANGE                       1:1
#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_WOFFSET                     0x0
#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_LOCALINTERRUPTSTATUS_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSR_0_WAKESTATUS_SHIFT                 _MK_SHIFT_CONST(2)
#define RTC2_AOWDTSR_0_WAKESTATUS_FIELD                 _MK_FIELD_CONST(0x1, RTC2_AOWDTSR_0_WAKESTATUS_SHIFT)
#define RTC2_AOWDTSR_0_WAKESTATUS_RANGE                 2:2
#define RTC2_AOWDTSR_0_WAKESTATUS_WOFFSET                       0x0
#define RTC2_AOWDTSR_0_WAKESTATUS_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_WAKESTATUS_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define RTC2_AOWDTSR_0_WAKESTATUS_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_WAKESTATUS_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_SHIFT                     _MK_SHIFT_CONST(3)
#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_FIELD                     _MK_FIELD_CONST(0x1, RTC2_AOWDTSR_0_WAKECOLDSTATUS_SHIFT)
#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_RANGE                     3:3
#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_WOFFSET                   0x0
#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_WAKECOLDSTATUS_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSR_0_CURRENTCOUNT_SHIFT                       _MK_SHIFT_CONST(4)
#define RTC2_AOWDTSR_0_CURRENTCOUNT_FIELD                       _MK_FIELD_CONST(0xff, RTC2_AOWDTSR_0_CURRENTCOUNT_SHIFT)
#define RTC2_AOWDTSR_0_CURRENTCOUNT_RANGE                       11:4
#define RTC2_AOWDTSR_0_CURRENTCOUNT_WOFFSET                     0x0
#define RTC2_AOWDTSR_0_CURRENTCOUNT_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_CURRENTCOUNT_DEFAULT_MASK                        _MK_MASK_CONST(0xff)
#define RTC2_AOWDTSR_0_CURRENTCOUNT_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_CURRENTCOUNT_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_SHIFT                     _MK_SHIFT_CONST(12)
#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_FIELD                     _MK_FIELD_CONST(0x7, RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_SHIFT)
#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_RANGE                     14:12
#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_WOFFSET                   0x0
#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_DEFAULT_MASK                      _MK_MASK_CONST(0x7)
#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_CURRENTEXPIRATIONCOUNT_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSR_0_CURRENTERROR_SHIFT                       _MK_SHIFT_CONST(16)
#define RTC2_AOWDTSR_0_CURRENTERROR_FIELD                       _MK_FIELD_CONST(0x1, RTC2_AOWDTSR_0_CURRENTERROR_SHIFT)
#define RTC2_AOWDTSR_0_CURRENTERROR_RANGE                       16:16
#define RTC2_AOWDTSR_0_CURRENTERROR_WOFFSET                     0x0
#define RTC2_AOWDTSR_0_CURRENTERROR_DEFAULT                     _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_CURRENTERROR_DEFAULT_MASK                        _MK_MASK_CONST(0x1)
#define RTC2_AOWDTSR_0_CURRENTERROR_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSR_0_CURRENTERROR_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register RTC2_AOWDTCMDR_0
#define RTC2_AOWDTCMDR_0                        _MK_ADDR_CONST(0x108)
#define RTC2_AOWDTCMDR_0_SECURE                         0x0
#define RTC2_AOWDTCMDR_0_SCR                    AOWDTSCR_0
#define RTC2_AOWDTCMDR_0_WORD_COUNT                     0x1
#define RTC2_AOWDTCMDR_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCMDR_0_RESET_MASK                     _MK_MASK_CONST(0x3)
#define RTC2_AOWDTCMDR_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCMDR_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCMDR_0_READ_MASK                      _MK_MASK_CONST(0x3)
#define RTC2_AOWDTCMDR_0_WRITE_MASK                     _MK_MASK_CONST(0x3)
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_SHIFT                     _MK_SHIFT_CONST(0)
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_FIELD                     _MK_FIELD_CONST(0x1, RTC2_AOWDTCMDR_0_STARTCOUNTER_SHIFT)
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_RANGE                     0:0
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_WOFFSET                   0x0
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCMDR_0_STARTCOUNTER_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)

#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_SHIFT                   _MK_SHIFT_CONST(1)
#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_FIELD                   _MK_FIELD_CONST(0x1, RTC2_AOWDTCMDR_0_DISABLECOUNTER_SHIFT)
#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_RANGE                   1:1
#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_WOFFSET                 0x0
#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define RTC2_AOWDTCMDR_0_DISABLECOUNTER_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register RTC2_AOWDTUR_0
#define RTC2_AOWDTUR_0                  _MK_ADDR_CONST(0x10c)
#define RTC2_AOWDTUR_0_SECURE                   0x0
#define RTC2_AOWDTUR_0_SCR                      AOWDTSCR_0
#define RTC2_AOWDTUR_0_WORD_COUNT                       0x1
#define RTC2_AOWDTUR_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTUR_0_RESET_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_AOWDTUR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define RTC2_AOWDTUR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTUR_0_READ_MASK                        _MK_MASK_CONST(0xffffffff)
#define RTC2_AOWDTUR_0_WRITE_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_SHIFT                      _MK_SHIFT_CONST(0)
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_FIELD                      _MK_FIELD_CONST(0xffffffff, RTC2_AOWDTUR_0_UNLOCKPATTERN_SHIFT)
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_RANGE                      31:0
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_WOFFSET                    0x0
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_DEFAULT                    _MK_MASK_CONST(0x0)
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_DEFAULT_MASK                       _MK_MASK_CONST(0xffffffff)
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_SW_DEFAULT                 _MK_MASK_CONST(0x0)
#define RTC2_AOWDTUR_0_UNLOCKPATTERN_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)


// Register RTC2_AOWDTSCOR_0
#define RTC2_AOWDTSCOR_0                        _MK_ADDR_CONST(0x110)
#define RTC2_AOWDTSCOR_0_SECURE                         0x0
#define RTC2_AOWDTSCOR_0_SCR                    AOWDTSCR_0
#define RTC2_AOWDTSCOR_0_WORD_COUNT                     0x1
#define RTC2_AOWDTSCOR_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_RESET_MASK                     _MK_MASK_CONST(0x7777)
#define RTC2_AOWDTSCOR_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_READ_MASK                      _MK_MASK_CONST(0x7777)
#define RTC2_AOWDTSCOR_0_WRITE_MASK                     _MK_MASK_CONST(0x7777)
#define RTC2_AOWDTSCOR_0_SKIP0_SHIFT                    _MK_SHIFT_CONST(0)
#define RTC2_AOWDTSCOR_0_SKIP0_FIELD                    _MK_FIELD_CONST(0x7, RTC2_AOWDTSCOR_0_SKIP0_SHIFT)
#define RTC2_AOWDTSCOR_0_SKIP0_RANGE                    2:0
#define RTC2_AOWDTSCOR_0_SKIP0_WOFFSET                  0x0
#define RTC2_AOWDTSCOR_0_SKIP0_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP0_DEFAULT_MASK                     _MK_MASK_CONST(0x7)
#define RTC2_AOWDTSCOR_0_SKIP0_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSCOR_0_SKIP1_SHIFT                    _MK_SHIFT_CONST(4)
#define RTC2_AOWDTSCOR_0_SKIP1_FIELD                    _MK_FIELD_CONST(0x7, RTC2_AOWDTSCOR_0_SKIP1_SHIFT)
#define RTC2_AOWDTSCOR_0_SKIP1_RANGE                    6:4
#define RTC2_AOWDTSCOR_0_SKIP1_WOFFSET                  0x0
#define RTC2_AOWDTSCOR_0_SKIP1_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP1_DEFAULT_MASK                     _MK_MASK_CONST(0x7)
#define RTC2_AOWDTSCOR_0_SKIP1_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP1_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSCOR_0_SKIP2_SHIFT                    _MK_SHIFT_CONST(8)
#define RTC2_AOWDTSCOR_0_SKIP2_FIELD                    _MK_FIELD_CONST(0x7, RTC2_AOWDTSCOR_0_SKIP2_SHIFT)
#define RTC2_AOWDTSCOR_0_SKIP2_RANGE                    10:8
#define RTC2_AOWDTSCOR_0_SKIP2_WOFFSET                  0x0
#define RTC2_AOWDTSCOR_0_SKIP2_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP2_DEFAULT_MASK                     _MK_MASK_CONST(0x7)
#define RTC2_AOWDTSCOR_0_SKIP2_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP2_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define RTC2_AOWDTSCOR_0_SKIP3_SHIFT                    _MK_SHIFT_CONST(12)
#define RTC2_AOWDTSCOR_0_SKIP3_FIELD                    _MK_FIELD_CONST(0x7, RTC2_AOWDTSCOR_0_SKIP3_SHIFT)
#define RTC2_AOWDTSCOR_0_SKIP3_RANGE                    14:12
#define RTC2_AOWDTSCOR_0_SKIP3_WOFFSET                  0x0
#define RTC2_AOWDTSCOR_0_SKIP3_DEFAULT                  _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP3_DEFAULT_MASK                     _MK_MASK_CONST(0x7)
#define RTC2_AOWDTSCOR_0_SKIP3_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define RTC2_AOWDTSCOR_0_SKIP3_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)


// Register RTC2_CLK_OVR_ON_0
#define RTC2_CLK_OVR_ON_0                       _MK_ADDR_CONST(0x114)
#define RTC2_CLK_OVR_ON_0_SECURE                        0x0
#define RTC2_CLK_OVR_ON_0_SCR                   RTCSCR_0
#define RTC2_CLK_OVR_ON_0_WORD_COUNT                    0x1
#define RTC2_CLK_OVR_ON_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define RTC2_CLK_OVR_ON_0_RESET_MASK                    _MK_MASK_CONST(0x1)
#define RTC2_CLK_OVR_ON_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define RTC2_CLK_OVR_ON_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define RTC2_CLK_OVR_ON_0_READ_MASK                     _MK_MASK_CONST(0x1)
#define RTC2_CLK_OVR_ON_0_WRITE_MASK                    _MK_MASK_CONST(0x1)
#define RTC2_CLK_OVR_ON_0_RTC_SHIFT                     _MK_SHIFT_CONST(0)
#define RTC2_CLK_OVR_ON_0_RTC_FIELD                     _MK_FIELD_CONST(0x1, RTC2_CLK_OVR_ON_0_RTC_SHIFT)
#define RTC2_CLK_OVR_ON_0_RTC_RANGE                     0:0
#define RTC2_CLK_OVR_ON_0_RTC_WOFFSET                   0x0
#define RTC2_CLK_OVR_ON_0_RTC_DEFAULT                   _MK_MASK_CONST(0x0)
#define RTC2_CLK_OVR_ON_0_RTC_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define RTC2_CLK_OVR_ON_0_RTC_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define RTC2_CLK_OVR_ON_0_RTC_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define RTC2_CLK_OVR_ON_0_RTC_DISABLE                   _MK_ENUM_CONST(0)
#define RTC2_CLK_OVR_ON_0_RTC_ENABLE                    _MK_ENUM_CONST(1)


//
// REGISTER LIST
//
#define LIST_ARRTC2_REGS(_op_) \
_op_(RTC2_RTCCR_0) \
_op_(RTC2_RTCBR_0) \
_op_(RTC2_RTCSCR_0) \
_op_(RTC2_RTCSSCR_0) \
_op_(RTC2_RTCMCR_0) \
_op_(RTC2_RTCSAR0_0) \
_op_(RTC2_RTCSAR1_0) \
_op_(RTC2_RTCMAR_0) \
_op_(RTC2_RTCSCAR_0) \
_op_(RTC2_RTCMCAR_0) \
_op_(RTC2_RTCIER_0) \
_op_(RTC2_RTCISR_0) \
_op_(RTC2_RTCIVR_0) \
_op_(RTC2_RTCFIR_0) \
_op_(RTC2_RTCRSR_0) \
_op_(RTC2_RTCDR_0) \
_op_(RTC2_AOWDTCR_0) \
_op_(RTC2_AOWDTSR_0) \
_op_(RTC2_AOWDTCMDR_0) \
_op_(RTC2_AOWDTUR_0) \
_op_(RTC2_AOWDTSCOR_0) \
_op_(RTC2_CLK_OVR_ON_0)


//
// ADDRESS SPACES
//

#define BASE_ADDRESS_RTC2       0x00000000

//
// ARRTC2 REGISTER BANKS
//

#define RTC20_FIRST_REG 0x0000 // RTC2_RTCCR_0
#define RTC20_LAST_REG 0x003c // RTC2_RTCDR_0
#define RTC21_FIRST_REG 0x0100 // RTC2_AOWDTCR_0
#define RTC21_LAST_REG 0x0114 // RTC2_CLK_OVR_ON_0

// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARRTC2_H_INC_
