//
// Copyright (c) 2015 NVIDIA Corporation.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARSCE_HSM_ERROR_H_INC_
#define ___ARSCE_HSM_ERROR_H_INC_
#define NV_SCE_HSM_ERROR_APE    0
#define NV_SCE_HSM_ERROR_RSVD01 1
#define NV_SCE_HSM_ERROR_CCPLEX 2
#define NV_SCE_HSM_ERROR_RSVD03 3
#define NV_SCE_HSM_ERROR_DRAM_ECC0      4
#define NV_SCE_HSM_ERROR_DRAM_ECC1      5
#define NV_SCE_HSM_ERROR_DISP_0 6
#define NV_SCE_HSM_ERROR_DISP_1 7
#define NV_SCE_HSM_ERROR_DISP_2 8
#define NV_SCE_HSM_ERROR_DISP_3 9
#define NV_SCE_HSM_ERROR_DISP_4 10
#define NV_SCE_HSM_ERROR_DISP_5 11
#define NV_SCE_HSM_ERROR_DISP_6 12
#define NV_SCE_HSM_ERROR_GPU    13
#define NV_SCE_HSM_ERROR_SIB_00 14
#define NV_SCE_HSM_ERROR_SIB_01 15
#define NV_SCE_HSM_ERROR_SIB_02 16
#define NV_SCE_HSM_ERROR_SIB_03 17
#define NV_SCE_HSM_ERROR_SIB_04 18
#define NV_SCE_HSM_ERROR_SIB_05 19
#define NV_SCE_HSM_ERROR_SIB_06 20
#define NV_SCE_HSM_ERROR_SIB_07 21
#define NV_SCE_HSM_ERROR_SIB_08 22
#define NV_SCE_HSM_ERROR_SIB_09 23
#define NV_SCE_HSM_ERROR_SIB_10 24
#define NV_SCE_HSM_ERROR_SIB_11 25
#define NV_SCE_HSM_ERROR_SIB_12 26
#define NV_SCE_HSM_ERROR_SIB_13 27
#define NV_SCE_HSM_ERROR_SIB_14 28
#define NV_SCE_HSM_ERROR_SIB_15 29
#define NV_SCE_HSM_ERROR_PMC    30
#define NV_SCE_HSM_ERROR_VI     31
#define NV_SCE_HSM_ERROR_CSI    32
#define NV_SCE_HSM_ERROR_ISP    33
#define NV_SCE_HSM_ERROR_HOST1X 34
#define NV_SCE_HSM_ERROR_SCE_HSM_TIMER  35
#define NV_SCE_HSM_ERROR_SCE_SC_FATAL_ERROR     36
#define NV_SCE_HSM_ERROR_SCE_AXI_ECC_ERR        37
#define NV_SCE_HSM_ERROR_SCE_HSM_FMON   38
#define NV_SCE_HSM_ERROR_SOC_THERM      39
#define NV_SCE_HSM_ERROR_TMON   40
#define NV_SCE_HSM_ERROR_VTG_CLK_MON    41
#define NV_SCE_HSM_ERROR_AOWDT  42
#define NV_SCE_HSM_ERROR_TKE_WDT_0      43
#define NV_SCE_HSM_ERROR_TKE_WDT_1      44
#define NV_SCE_HSM_ERROR_TKE_WDT_2      45
#define NV_SCE_HSM_ERROR_TKE_WDT_3      46
#define NV_SCE_HSM_ERROR_TKE_WDT_4      47
#define NV_SCE_HSM_ERROR_TKE_WDT_5      48
#define NV_SCE_HSM_ERROR_TKE_WDT_6      49
#define NV_SCE_HSM_ERROR_HSIO_PCIE      50
#define NV_SCE_HSM_ERROR_LSIO_SPI_0     51
#define NV_SCE_HSM_ERROR_LSIO_SPI_1     52
#define NV_SCE_HSM_ERROR_LSIO_SPI_2     53
#define NV_SCE_HSM_ERROR_HSIO_XUSB_0    54
#define NV_SCE_HSM_ERROR_HSIO_XUSB_1    55
#define NV_SCE_HSM_ERROR_AON_CAN0       56
#define NV_SCE_HSM_ERROR_AON_CAN1       57
#define NV_SCE_HSM_ERROR_AON_SPI        58
#define NV_SCE_HSM_ERROR_AON_VFMON      59
#define NV_SCE_HSM_ERROR_SIB_16 60
#define NV_SCE_HSM_ERROR_SIB_17 61
#define NV_SCE_HSM_ERROR_RSVD62 62
#define NV_SCE_HSM_ERROR_RSVD63 63
#define NV_SCE_HSM_ERROR_RSVD64 64
#define NV_SCE_HSM_ERROR_RSVD65 65
#define NV_SCE_HSM_ERROR_RSVD66 66
#define NV_SCE_HSM_ERROR_RSVD67 67
#define NV_SCE_HSM_ERROR_RSVD68 68
#define NV_SCE_HSM_ERROR_RSVD69 69
#define NV_SCE_HSM_ERROR_RSVD70 70
#define NV_SCE_HSM_ERROR_RSVD71 71
#define NV_SCE_HSM_ERROR_RSVD72 72
#define NV_SCE_HSM_ERROR_RSVD73 73
#define NV_SCE_HSM_ERROR_RSVD74 74
#define NV_SCE_HSM_ERROR_RSVD75 75
#define NV_SCE_HSM_ERROR_RSVD76 76
#define NV_SCE_HSM_ERROR_RSVD77 77
#define NV_SCE_HSM_ERROR_RSVD78 78
#define NV_SCE_HSM_ERROR_RSVD79 79
#define NV_SCE_HSM_ERROR_RSVD80 80
#define NV_SCE_HSM_ERROR_RSVD81 81
#define NV_SCE_HSM_ERROR_RSVD82 82
#define NV_SCE_HSM_ERROR_RSVD83 83
#define NV_SCE_HSM_ERROR_RSVD84 84
#define NV_SCE_HSM_ERROR_RSVD85 85
#define NV_SCE_HSM_ERROR_RSVD86 86
#define NV_SCE_HSM_ERROR_RSVD87 87
#define NV_SCE_HSM_ERROR_RSVD88 88
#define NV_SCE_HSM_ERROR_RSVD89 89
#define NV_SCE_HSM_ERROR_RSVD90 90
#define NV_SCE_HSM_ERROR_RSVD91 91
#define NV_SCE_HSM_ERROR_RSVD92 92
#define NV_SCE_HSM_ERROR_RSVD93 93
#define NV_SCE_HSM_ERROR_RSVD94 94
#define NV_SCE_HSM_ERROR_RSVD95 95
#define NV_SCE_HSM_ERROR_RSVD96 96

//
// ADDRESS SPACES
//


//
// ARSCE_HSM_ERROR REGISTER BANKS
//


// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARSCE_HSM_ERROR_H_INC_
