//
// Copyright (c) 2016 NVIDIA Corporation.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//  * Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
//  * Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
//  * Neither the name of NVIDIA CORPORATION nor the names of its
//    contributors may be used to endorse or promote products derived
//    from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS ``AS IS'' AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
// PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR
// CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
// EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
// PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
// OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARTSC_H_INC_
#define ___ARTSC_H_INC_

// Register TSC_MTSCACR_0
#define TSC_MTSCACR_0                   _MK_ADDR_CONST(0x0)
#define TSC_MTSCACR_0_SECURE                    0x0
#define TSC_MTSCACR_0_SCR                       TSCSCR_0
#define TSC_MTSCACR_0_WORD_COUNT                        0x1
#define TSC_MTSCACR_0_RESET_VAL                         _MK_MASK_CONST(0x2)
#define TSC_MTSCACR_0_RESET_MASK                        _MK_MASK_CONST(0xf3)
#define TSC_MTSCACR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_READ_MASK                         _MK_MASK_CONST(0xf3)
#define TSC_MTSCACR_0_WRITE_MASK                        _MK_MASK_CONST(0xf3)
#define TSC_MTSCACR_0_EN_SHIFT                  _MK_SHIFT_CONST(0)
#define TSC_MTSCACR_0_EN_FIELD                  _MK_FIELD_CONST(0x1, TSC_MTSCACR_0_EN_SHIFT)
#define TSC_MTSCACR_0_EN_RANGE                  0:0
#define TSC_MTSCACR_0_EN_WOFFSET                        0x0
#define TSC_MTSCACR_0_EN_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_EN_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define TSC_MTSCACR_0_EN_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_EN_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_EN_DISABLE                        _MK_ENUM_CONST(0)
#define TSC_MTSCACR_0_EN_ENABLE                 _MK_ENUM_CONST(1)

#define TSC_MTSCACR_0_DIR_SHIFT                 _MK_SHIFT_CONST(1)
#define TSC_MTSCACR_0_DIR_FIELD                 _MK_FIELD_CONST(0x1, TSC_MTSCACR_0_DIR_SHIFT)
#define TSC_MTSCACR_0_DIR_RANGE                 1:1
#define TSC_MTSCACR_0_DIR_WOFFSET                       0x0
#define TSC_MTSCACR_0_DIR_DEFAULT                       _MK_MASK_CONST(0x1)
#define TSC_MTSCACR_0_DIR_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define TSC_MTSCACR_0_DIR_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_DIR_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define TSC_MTSCACR_0_ABS_SHIFT                 _MK_SHIFT_CONST(4)
#define TSC_MTSCACR_0_ABS_FIELD                 _MK_FIELD_CONST(0xf, TSC_MTSCACR_0_ABS_SHIFT)
#define TSC_MTSCACR_0_ABS_RANGE                 7:4
#define TSC_MTSCACR_0_ABS_WOFFSET                       0x0
#define TSC_MTSCACR_0_ABS_DEFAULT                       _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_ABS_DEFAULT_MASK                  _MK_MASK_CONST(0xf)
#define TSC_MTSCACR_0_ABS_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define TSC_MTSCACR_0_ABS_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register TSC_MTSCADR_0
#define TSC_MTSCADR_0                   _MK_ADDR_CONST(0x4)
#define TSC_MTSCADR_0_SECURE                    0x0
#define TSC_MTSCADR_0_SCR                       TSCSCR_0
#define TSC_MTSCADR_0_WORD_COUNT                        0x1
#define TSC_MTSCADR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define TSC_MTSCADR_0_RESET_MASK                        _MK_MASK_CONST(0xfff0fff)
#define TSC_MTSCADR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define TSC_MTSCADR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define TSC_MTSCADR_0_READ_MASK                         _MK_MASK_CONST(0xfff0fff)
#define TSC_MTSCADR_0_WRITE_MASK                        _MK_MASK_CONST(0xfff0fff)
#define TSC_MTSCADR_0_N1_SHIFT                  _MK_SHIFT_CONST(0)
#define TSC_MTSCADR_0_N1_FIELD                  _MK_FIELD_CONST(0xfff, TSC_MTSCADR_0_N1_SHIFT)
#define TSC_MTSCADR_0_N1_RANGE                  11:0
#define TSC_MTSCADR_0_N1_WOFFSET                        0x0
#define TSC_MTSCADR_0_N1_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_MTSCADR_0_N1_DEFAULT_MASK                   _MK_MASK_CONST(0xfff)
#define TSC_MTSCADR_0_N1_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_MTSCADR_0_N1_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define TSC_MTSCADR_0_D1_SHIFT                  _MK_SHIFT_CONST(16)
#define TSC_MTSCADR_0_D1_FIELD                  _MK_FIELD_CONST(0xfff, TSC_MTSCADR_0_D1_SHIFT)
#define TSC_MTSCADR_0_D1_RANGE                  27:16
#define TSC_MTSCADR_0_D1_WOFFSET                        0x0
#define TSC_MTSCADR_0_D1_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_MTSCADR_0_D1_DEFAULT_MASK                   _MK_MASK_CONST(0xfff)
#define TSC_MTSCADR_0_D1_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_MTSCADR_0_D1_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)


// Register TSC_MTSCANNR_0
#define TSC_MTSCANNR_0                  _MK_ADDR_CONST(0x8)
#define TSC_MTSCANNR_0_SECURE                   0x0
#define TSC_MTSCANNR_0_SCR                      TSCSCR_0
#define TSC_MTSCANNR_0_WORD_COUNT                       0x1
#define TSC_MTSCANNR_0_RESET_VAL                        _MK_MASK_CONST(0x56503b9)
#define TSC_MTSCANNR_0_RESET_MASK                       _MK_MASK_CONST(0xfff0fff)
#define TSC_MTSCANNR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define TSC_MTSCANNR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define TSC_MTSCANNR_0_READ_MASK                        _MK_MASK_CONST(0xfff0fff)
#define TSC_MTSCANNR_0_WRITE_MASK                       _MK_MASK_CONST(0xfff0fff)
#define TSC_MTSCANNR_0_R0_SHIFT                 _MK_SHIFT_CONST(0)
#define TSC_MTSCANNR_0_R0_FIELD                 _MK_FIELD_CONST(0xfff, TSC_MTSCANNR_0_R0_SHIFT)
#define TSC_MTSCANNR_0_R0_RANGE                 11:0
#define TSC_MTSCANNR_0_R0_WOFFSET                       0x0
#define TSC_MTSCANNR_0_R0_DEFAULT                       _MK_MASK_CONST(0x3b9)
#define TSC_MTSCANNR_0_R0_DEFAULT_MASK                  _MK_MASK_CONST(0xfff)
#define TSC_MTSCANNR_0_R0_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define TSC_MTSCANNR_0_R0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define TSC_MTSCANNR_0_M0_SHIFT                 _MK_SHIFT_CONST(16)
#define TSC_MTSCANNR_0_M0_FIELD                 _MK_FIELD_CONST(0xfff, TSC_MTSCANNR_0_M0_SHIFT)
#define TSC_MTSCANNR_0_M0_RANGE                 27:16
#define TSC_MTSCANNR_0_M0_WOFFSET                       0x0
#define TSC_MTSCANNR_0_M0_DEFAULT                       _MK_MASK_CONST(0x565)
#define TSC_MTSCANNR_0_M0_DEFAULT_MASK                  _MK_MASK_CONST(0xfff)
#define TSC_MTSCANNR_0_M0_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define TSC_MTSCANNR_0_M0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register TSC_MTSCANDR_0
#define TSC_MTSCANDR_0                  _MK_ADDR_CONST(0xc)
#define TSC_MTSCANDR_0_SECURE                   0x0
#define TSC_MTSCANDR_0_SCR                      TSCSCR_0
#define TSC_MTSCANDR_0_WORD_COUNT                       0x1
#define TSC_MTSCANDR_0_RESET_VAL                        _MK_MASK_CONST(0x800)
#define TSC_MTSCANDR_0_RESET_MASK                       _MK_MASK_CONST(0xfff)
#define TSC_MTSCANDR_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define TSC_MTSCANDR_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define TSC_MTSCANDR_0_READ_MASK                        _MK_MASK_CONST(0xfff)
#define TSC_MTSCANDR_0_WRITE_MASK                       _MK_MASK_CONST(0xfff)
#define TSC_MTSCANDR_0_D0_SHIFT                 _MK_SHIFT_CONST(0)
#define TSC_MTSCANDR_0_D0_FIELD                 _MK_FIELD_CONST(0xfff, TSC_MTSCANDR_0_D0_SHIFT)
#define TSC_MTSCANDR_0_D0_RANGE                 11:0
#define TSC_MTSCANDR_0_D0_WOFFSET                       0x0
#define TSC_MTSCANDR_0_D0_DEFAULT                       _MK_MASK_CONST(0x800)
#define TSC_MTSCANDR_0_D0_DEFAULT_MASK                  _MK_MASK_CONST(0xfff)
#define TSC_MTSCANDR_0_D0_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define TSC_MTSCANDR_0_D0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)


// Register TSC_MTSCCNTCV0_0
#define TSC_MTSCCNTCV0_0                        _MK_ADDR_CONST(0x10)
#define TSC_MTSCCNTCV0_0_SECURE                         0x0
#define TSC_MTSCCNTCV0_0_SCR                    TSCSCR_0
#define TSC_MTSCCNTCV0_0_WORD_COUNT                     0x1
#define TSC_MTSCCNTCV0_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV0_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define TSC_MTSCCNTCV0_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV0_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV0_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define TSC_MTSCCNTCV0_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV0_0_CV_SHIFT                       _MK_SHIFT_CONST(0)
#define TSC_MTSCCNTCV0_0_CV_FIELD                       _MK_FIELD_CONST(0xffffffff, TSC_MTSCCNTCV0_0_CV_SHIFT)
#define TSC_MTSCCNTCV0_0_CV_RANGE                       31:0
#define TSC_MTSCCNTCV0_0_CV_WOFFSET                     0x0
#define TSC_MTSCCNTCV0_0_CV_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV0_0_CV_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define TSC_MTSCCNTCV0_0_CV_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV0_0_CV_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register TSC_MTSCCNTCV1_0
#define TSC_MTSCCNTCV1_0                        _MK_ADDR_CONST(0x14)
#define TSC_MTSCCNTCV1_0_SECURE                         0x0
#define TSC_MTSCCNTCV1_0_SCR                    TSCSCR_0
#define TSC_MTSCCNTCV1_0_WORD_COUNT                     0x1
#define TSC_MTSCCNTCV1_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV1_0_RESET_MASK                     _MK_MASK_CONST(0xffffffff)
#define TSC_MTSCCNTCV1_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV1_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV1_0_READ_MASK                      _MK_MASK_CONST(0xffffffff)
#define TSC_MTSCCNTCV1_0_WRITE_MASK                     _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV1_0_CV_SHIFT                       _MK_SHIFT_CONST(0)
#define TSC_MTSCCNTCV1_0_CV_FIELD                       _MK_FIELD_CONST(0xffffffff, TSC_MTSCCNTCV1_0_CV_SHIFT)
#define TSC_MTSCCNTCV1_0_CV_RANGE                       31:0
#define TSC_MTSCCNTCV1_0_CV_WOFFSET                     0x0
#define TSC_MTSCCNTCV1_0_CV_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV1_0_CV_DEFAULT_MASK                        _MK_MASK_CONST(0xffffffff)
#define TSC_MTSCCNTCV1_0_CV_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define TSC_MTSCCNTCV1_0_CV_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Reserved address 24 [0x18]

// Reserved address 28 [0x1c]

// Reserved address 32 [0x20]

// Reserved address 36 [0x24]

// Reserved address 40 [0x28]

// Reserved address 44 [0x2c]

// Reserved address 48 [0x30]

// Reserved address 52 [0x34]

// Reserved address 56 [0x38]

// Reserved address 60 [0x3c]

// Reserved address 64 [0x40]

// Reserved address 68 [0x44]

// Reserved address 72 [0x48]

// Reserved address 76 [0x4c]

// Reserved address 80 [0x50]

// Reserved address 84 [0x54]

// Reserved address 88 [0x58]

// Reserved address 92 [0x5c]

// Reserved address 96 [0x60]

// Reserved address 100 [0x64]

// Reserved address 104 [0x68]

// Reserved address 108 [0x6c]

// Reserved address 112 [0x70]

// Reserved address 116 [0x74]

// Reserved address 120 [0x78]

// Reserved address 124 [0x7c]

// Reserved address 128 [0x80]

// Reserved address 132 [0x84]

// Reserved address 136 [0x88]

// Reserved address 140 [0x8c]

// Reserved address 144 [0x90]

// Reserved address 148 [0x94]

// Reserved address 152 [0x98]

// Reserved address 156 [0x9c]

// Reserved address 160 [0xa0]

// Reserved address 164 [0xa4]

// Reserved address 168 [0xa8]

// Reserved address 172 [0xac]

// Reserved address 176 [0xb0]

// Reserved address 180 [0xb4]

// Reserved address 184 [0xb8]

// Reserved address 188 [0xbc]

// Reserved address 192 [0xc0]

// Reserved address 196 [0xc4]

// Reserved address 200 [0xc8]

// Reserved address 204 [0xcc]

// Reserved address 208 [0xd0]

// Reserved address 212 [0xd4]

// Reserved address 216 [0xd8]

// Reserved address 220 [0xdc]

// Reserved address 224 [0xe0]

// Reserved address 228 [0xe4]

// Reserved address 232 [0xe8]

// Reserved address 236 [0xec]

// Reserved address 240 [0xf0]

// Reserved address 244 [0xf4]

// Reserved address 248 [0xf8]

// Reserved address 252 [0xfc]

// Register TSC_STSCCR_0
#define TSC_STSCCR_0                    _MK_ADDR_CONST(0x100)
#define TSC_STSCCR_0_SECURE                     0x0
#define TSC_STSCCR_0_SCR                        TSCSCR_0
#define TSC_STSCCR_0_WORD_COUNT                         0x1
#define TSC_STSCCR_0_RESET_VAL                  _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_RESET_MASK                         _MK_MASK_CONST(0x12f)
#define TSC_STSCCR_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_READ_MASK                  _MK_MASK_CONST(0x12f)
#define TSC_STSCCR_0_WRITE_MASK                         _MK_MASK_CONST(0x12f)
#define TSC_STSCCR_0_INIT_SHIFT                 _MK_SHIFT_CONST(0)
#define TSC_STSCCR_0_INIT_FIELD                 _MK_FIELD_CONST(0x1, TSC_STSCCR_0_INIT_SHIFT)
#define TSC_STSCCR_0_INIT_RANGE                 0:0
#define TSC_STSCCR_0_INIT_WOFFSET                       0x0
#define TSC_STSCCR_0_INIT_DEFAULT                       _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_INIT_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define TSC_STSCCR_0_INIT_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_INIT_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define TSC_STSCCR_0_DIS_SHIFT                  _MK_SHIFT_CONST(1)
#define TSC_STSCCR_0_DIS_FIELD                  _MK_FIELD_CONST(0x1, TSC_STSCCR_0_DIS_SHIFT)
#define TSC_STSCCR_0_DIS_RANGE                  1:1
#define TSC_STSCCR_0_DIS_WOFFSET                        0x0
#define TSC_STSCCR_0_DIS_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_DIS_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define TSC_STSCCR_0_DIS_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_DIS_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define TSC_STSCCR_0_FP_SHIFT                   _MK_SHIFT_CONST(2)
#define TSC_STSCCR_0_FP_FIELD                   _MK_FIELD_CONST(0x1, TSC_STSCCR_0_FP_SHIFT)
#define TSC_STSCCR_0_FP_RANGE                   2:2
#define TSC_STSCCR_0_FP_WOFFSET                 0x0
#define TSC_STSCCR_0_FP_DEFAULT                 _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_FP_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define TSC_STSCCR_0_FP_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_FP_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)

#define TSC_STSCCR_0_SRC_SHIFT                  _MK_SHIFT_CONST(3)
#define TSC_STSCCR_0_SRC_FIELD                  _MK_FIELD_CONST(0x1, TSC_STSCCR_0_SRC_SHIFT)
#define TSC_STSCCR_0_SRC_RANGE                  3:3
#define TSC_STSCCR_0_SRC_WOFFSET                        0x0
#define TSC_STSCCR_0_SRC_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_SRC_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define TSC_STSCCR_0_SRC_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_SRC_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define TSC_STSCCR_0_FCREQ_DISABLE_SHIFT                        _MK_SHIFT_CONST(5)
#define TSC_STSCCR_0_FCREQ_DISABLE_FIELD                        _MK_FIELD_CONST(0x1, TSC_STSCCR_0_FCREQ_DISABLE_SHIFT)
#define TSC_STSCCR_0_FCREQ_DISABLE_RANGE                        5:5
#define TSC_STSCCR_0_FCREQ_DISABLE_WOFFSET                      0x0
#define TSC_STSCCR_0_FCREQ_DISABLE_DEFAULT                      _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_FCREQ_DISABLE_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define TSC_STSCCR_0_FCREQ_DISABLE_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_FCREQ_DISABLE_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_FCREQ_DISABLE_DISABLE                      _MK_ENUM_CONST(0)
#define TSC_STSCCR_0_FCREQ_DISABLE_ENABLE                       _MK_ENUM_CONST(1)

#define TSC_STSCCR_0_FCREQ_SHIFT                        _MK_SHIFT_CONST(8)
#define TSC_STSCCR_0_FCREQ_FIELD                        _MK_FIELD_CONST(0x1, TSC_STSCCR_0_FCREQ_SHIFT)
#define TSC_STSCCR_0_FCREQ_RANGE                        8:8
#define TSC_STSCCR_0_FCREQ_WOFFSET                      0x0
#define TSC_STSCCR_0_FCREQ_DEFAULT                      _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_FCREQ_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define TSC_STSCCR_0_FCREQ_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define TSC_STSCCR_0_FCREQ_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)


// Register TSC_STSCRSR_0
#define TSC_STSCRSR_0                   _MK_ADDR_CONST(0x104)
#define TSC_STSCRSR_0_SECURE                    0x0
#define TSC_STSCRSR_0_SCR                       TSCSCR_0
#define TSC_STSCRSR_0_WORD_COUNT                        0x1
#define TSC_STSCRSR_0_RESET_VAL                         _MK_MASK_CONST(0x0)
#define TSC_STSCRSR_0_RESET_MASK                        _MK_MASK_CONST(0x1)
#define TSC_STSCRSR_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define TSC_STSCRSR_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define TSC_STSCRSR_0_READ_MASK                         _MK_MASK_CONST(0x1)
#define TSC_STSCRSR_0_WRITE_MASK                        _MK_MASK_CONST(0x1)
#define TSC_STSCRSR_0_FR_SHIFT                  _MK_SHIFT_CONST(0)
#define TSC_STSCRSR_0_FR_FIELD                  _MK_FIELD_CONST(0x1, TSC_STSCRSR_0_FR_SHIFT)
#define TSC_STSCRSR_0_FR_RANGE                  0:0
#define TSC_STSCRSR_0_FR_WOFFSET                        0x0
#define TSC_STSCRSR_0_FR_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_STSCRSR_0_FR_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define TSC_STSCRSR_0_FR_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_STSCRSR_0_FR_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define TSC_STSCRSR_0_FR_LOCKEN                 _MK_ENUM_CONST(0)
#define TSC_STSCRSR_0_FR_LOCKDIS                        _MK_ENUM_CONST(1)


// Register TSC_STSCIR0_0
#define TSC_STSCIR0_0                   _MK_ADDR_CONST(0x108)
#define TSC_STSCIR0_0_SECURE                    0x0
#define TSC_STSCIR0_0_SCR                       TSCSCR_0
#define TSC_STSCIR0_0_WORD_COUNT                        0x1
#define TSC_STSCIR0_0_RESET_VAL                         _MK_MASK_CONST(0x1)
#define TSC_STSCIR0_0_RESET_MASK                        _MK_MASK_CONST(0xf)
#define TSC_STSCIR0_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define TSC_STSCIR0_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define TSC_STSCIR0_0_READ_MASK                         _MK_MASK_CONST(0xf)
#define TSC_STSCIR0_0_WRITE_MASK                        _MK_MASK_CONST(0xf)
#define TSC_STSCIR0_0_K_SHIFT                   _MK_SHIFT_CONST(0)
#define TSC_STSCIR0_0_K_FIELD                   _MK_FIELD_CONST(0xf, TSC_STSCIR0_0_K_SHIFT)
#define TSC_STSCIR0_0_K_RANGE                   3:0
#define TSC_STSCIR0_0_K_WOFFSET                 0x0
#define TSC_STSCIR0_0_K_DEFAULT                 _MK_MASK_CONST(0x1)
#define TSC_STSCIR0_0_K_DEFAULT_MASK                    _MK_MASK_CONST(0xf)
#define TSC_STSCIR0_0_K_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define TSC_STSCIR0_0_K_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register TSC_STSCIR1_0
#define TSC_STSCIR1_0                   _MK_ADDR_CONST(0x10c)
#define TSC_STSCIR1_0_SECURE                    0x0
#define TSC_STSCIR1_0_SCR                       TSCSCR_0
#define TSC_STSCIR1_0_WORD_COUNT                        0x1
#define TSC_STSCIR1_0_RESET_VAL                         _MK_MASK_CONST(0x1)
#define TSC_STSCIR1_0_RESET_MASK                        _MK_MASK_CONST(0xf)
#define TSC_STSCIR1_0_SW_DEFAULT_VAL                    _MK_MASK_CONST(0x0)
#define TSC_STSCIR1_0_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define TSC_STSCIR1_0_READ_MASK                         _MK_MASK_CONST(0xf)
#define TSC_STSCIR1_0_WRITE_MASK                        _MK_MASK_CONST(0xf)
#define TSC_STSCIR1_0_K_SHIFT                   _MK_SHIFT_CONST(0)
#define TSC_STSCIR1_0_K_FIELD                   _MK_FIELD_CONST(0xf, TSC_STSCIR1_0_K_SHIFT)
#define TSC_STSCIR1_0_K_RANGE                   3:0
#define TSC_STSCIR1_0_K_WOFFSET                 0x0
#define TSC_STSCIR1_0_K_DEFAULT                 _MK_MASK_CONST(0x1)
#define TSC_STSCIR1_0_K_DEFAULT_MASK                    _MK_MASK_CONST(0xf)
#define TSC_STSCIR1_0_K_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define TSC_STSCIR1_0_K_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)


// Register TSC_STSCSR_0
#define TSC_STSCSR_0                    _MK_ADDR_CONST(0x110)
#define TSC_STSCSR_0_SECURE                     0x0
#define TSC_STSCSR_0_SCR                        TSCSCR_0
#define TSC_STSCSR_0_WORD_COUNT                         0x1
#define TSC_STSCSR_0_RESET_VAL                  _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_RESET_MASK                         _MK_MASK_CONST(0x1ff)
#define TSC_STSCSR_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_READ_MASK                  _MK_MASK_CONST(0x1ff)
#define TSC_STSCSR_0_WRITE_MASK                         _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_OFS_SHIFT                  _MK_SHIFT_CONST(0)
#define TSC_STSCSR_0_OFS_FIELD                  _MK_FIELD_CONST(0xff, TSC_STSCSR_0_OFS_SHIFT)
#define TSC_STSCSR_0_OFS_RANGE                  7:0
#define TSC_STSCSR_0_OFS_WOFFSET                        0x0
#define TSC_STSCSR_0_OFS_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_OFS_DEFAULT_MASK                   _MK_MASK_CONST(0xff)
#define TSC_STSCSR_0_OFS_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_OFS_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define TSC_STSCSR_0_FCACK_SHIFT                        _MK_SHIFT_CONST(8)
#define TSC_STSCSR_0_FCACK_FIELD                        _MK_FIELD_CONST(0x1, TSC_STSCSR_0_FCACK_SHIFT)
#define TSC_STSCSR_0_FCACK_RANGE                        8:8
#define TSC_STSCSR_0_FCACK_WOFFSET                      0x0
#define TSC_STSCSR_0_FCACK_DEFAULT                      _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_FCACK_DEFAULT_MASK                 _MK_MASK_CONST(0x1)
#define TSC_STSCSR_0_FCACK_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define TSC_STSCSR_0_FCACK_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)


// Register TSC_TSCDCR_0
#define TSC_TSCDCR_0                    _MK_ADDR_CONST(0x114)
#define TSC_TSCDCR_0_SECURE                     0x0
#define TSC_TSCDCR_0_SCR                        TSCSCR_0
#define TSC_TSCDCR_0_WORD_COUNT                         0x1
#define TSC_TSCDCR_0_RESET_VAL                  _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_RESET_MASK                         _MK_MASK_CONST(0xf037f)
#define TSC_TSCDCR_0_SW_DEFAULT_VAL                     _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_SW_DEFAULT_MASK                    _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_READ_MASK                  _MK_MASK_CONST(0xf037f)
#define TSC_TSCDCR_0_WRITE_MASK                         _MK_MASK_CONST(0xf037f)
#define TSC_TSCDCR_0_K_SHIFT                    _MK_SHIFT_CONST(0)
#define TSC_TSCDCR_0_K_FIELD                    _MK_FIELD_CONST(0xf, TSC_TSCDCR_0_K_SHIFT)
#define TSC_TSCDCR_0_K_RANGE                    3:0
#define TSC_TSCDCR_0_K_WOFFSET                  0x0
#define TSC_TSCDCR_0_K_DEFAULT                  _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_K_DEFAULT_MASK                     _MK_MASK_CONST(0xf)
#define TSC_TSCDCR_0_K_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_K_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)

#define TSC_TSCDCR_0_EN_SHIFT                   _MK_SHIFT_CONST(4)
#define TSC_TSCDCR_0_EN_FIELD                   _MK_FIELD_CONST(0x1, TSC_TSCDCR_0_EN_SHIFT)
#define TSC_TSCDCR_0_EN_RANGE                   4:4
#define TSC_TSCDCR_0_EN_WOFFSET                 0x0
#define TSC_TSCDCR_0_EN_DEFAULT                 _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_EN_DEFAULT_MASK                    _MK_MASK_CONST(0x1)
#define TSC_TSCDCR_0_EN_SW_DEFAULT                      _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_EN_SW_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_EN_DISABLE                 _MK_ENUM_CONST(0)
#define TSC_TSCDCR_0_EN_ENABLE                  _MK_ENUM_CONST(1)

#define TSC_TSCDCR_0_SYNC_SHIFT                 _MK_SHIFT_CONST(5)
#define TSC_TSCDCR_0_SYNC_FIELD                 _MK_FIELD_CONST(0x1, TSC_TSCDCR_0_SYNC_SHIFT)
#define TSC_TSCDCR_0_SYNC_RANGE                 5:5
#define TSC_TSCDCR_0_SYNC_WOFFSET                       0x0
#define TSC_TSCDCR_0_SYNC_DEFAULT                       _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_SYNC_DEFAULT_MASK                  _MK_MASK_CONST(0x1)
#define TSC_TSCDCR_0_SYNC_SW_DEFAULT                    _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_SYNC_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)

#define TSC_TSCDCR_0_DISABLE_PERIODIC_SHIFT                     _MK_SHIFT_CONST(6)
#define TSC_TSCDCR_0_DISABLE_PERIODIC_FIELD                     _MK_FIELD_CONST(0x1, TSC_TSCDCR_0_DISABLE_PERIODIC_SHIFT)
#define TSC_TSCDCR_0_DISABLE_PERIODIC_RANGE                     6:6
#define TSC_TSCDCR_0_DISABLE_PERIODIC_WOFFSET                   0x0
#define TSC_TSCDCR_0_DISABLE_PERIODIC_DEFAULT                   _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_DISABLE_PERIODIC_DEFAULT_MASK                      _MK_MASK_CONST(0x1)
#define TSC_TSCDCR_0_DISABLE_PERIODIC_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_DISABLE_PERIODIC_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_DISABLE_PERIODIC_DISABLE                   _MK_ENUM_CONST(0)
#define TSC_TSCDCR_0_DISABLE_PERIODIC_ENABLE                    _MK_ENUM_CONST(1)

#define TSC_TSCDCR_0_RES_SHIFT                  _MK_SHIFT_CONST(8)
#define TSC_TSCDCR_0_RES_FIELD                  _MK_FIELD_CONST(0x3, TSC_TSCDCR_0_RES_SHIFT)
#define TSC_TSCDCR_0_RES_RANGE                  9:8
#define TSC_TSCDCR_0_RES_WOFFSET                        0x0
#define TSC_TSCDCR_0_RES_DEFAULT                        _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_RES_DEFAULT_MASK                   _MK_MASK_CONST(0x3)
#define TSC_TSCDCR_0_RES_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_RES_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)

#define TSC_TSCDCR_0_SYNCEP_SHIFT                       _MK_SHIFT_CONST(16)
#define TSC_TSCDCR_0_SYNCEP_FIELD                       _MK_FIELD_CONST(0xf, TSC_TSCDCR_0_SYNCEP_SHIFT)
#define TSC_TSCDCR_0_SYNCEP_RANGE                       19:16
#define TSC_TSCDCR_0_SYNCEP_WOFFSET                     0x0
#define TSC_TSCDCR_0_SYNCEP_DEFAULT                     _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_SYNCEP_DEFAULT_MASK                        _MK_MASK_CONST(0xf)
#define TSC_TSCDCR_0_SYNCEP_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define TSC_TSCDCR_0_SYNCEP_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)


// Register TSC_CLK_OVR_ON_0
#define TSC_CLK_OVR_ON_0                        _MK_ADDR_CONST(0x118)
#define TSC_CLK_OVR_ON_0_SECURE                         0x0
#define TSC_CLK_OVR_ON_0_SCR                    TSCSCR_0
#define TSC_CLK_OVR_ON_0_WORD_COUNT                     0x1
#define TSC_CLK_OVR_ON_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define TSC_CLK_OVR_ON_0_RESET_MASK                     _MK_MASK_CONST(0x1)
#define TSC_CLK_OVR_ON_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define TSC_CLK_OVR_ON_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define TSC_CLK_OVR_ON_0_READ_MASK                      _MK_MASK_CONST(0x1)
#define TSC_CLK_OVR_ON_0_WRITE_MASK                     _MK_MASK_CONST(0x1)
#define TSC_CLK_OVR_ON_0_CK32K_SHIFT                    _MK_SHIFT_CONST(0)
#define TSC_CLK_OVR_ON_0_CK32K_FIELD                    _MK_FIELD_CONST(0x1, TSC_CLK_OVR_ON_0_CK32K_SHIFT)
#define TSC_CLK_OVR_ON_0_CK32K_RANGE                    0:0
#define TSC_CLK_OVR_ON_0_CK32K_WOFFSET                  0x0
#define TSC_CLK_OVR_ON_0_CK32K_DEFAULT                  _MK_MASK_CONST(0x0)
#define TSC_CLK_OVR_ON_0_CK32K_DEFAULT_MASK                     _MK_MASK_CONST(0x1)
#define TSC_CLK_OVR_ON_0_CK32K_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define TSC_CLK_OVR_ON_0_CK32K_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define TSC_CLK_OVR_ON_0_CK32K_DISABLE                  _MK_ENUM_CONST(0)
#define TSC_CLK_OVR_ON_0_CK32K_ENABLE                   _MK_ENUM_CONST(1)


//
// REGISTER LIST
//
#define LIST_ARTSC_REGS(_op_) \
_op_(TSC_MTSCACR_0) \
_op_(TSC_MTSCADR_0) \
_op_(TSC_MTSCANNR_0) \
_op_(TSC_MTSCANDR_0) \
_op_(TSC_MTSCCNTCV0_0) \
_op_(TSC_MTSCCNTCV1_0) \
_op_(TSC_STSCCR_0) \
_op_(TSC_STSCRSR_0) \
_op_(TSC_STSCIR0_0) \
_op_(TSC_STSCIR1_0) \
_op_(TSC_STSCSR_0) \
_op_(TSC_TSCDCR_0) \
_op_(TSC_CLK_OVR_ON_0)


//
// ADDRESS SPACES
//

#define BASE_ADDRESS_TSC        0x00000000

//
// ARTSC REGISTER BANKS
//

#define TSC0_FIRST_REG 0x0000 // TSC_MTSCACR_0
#define TSC0_LAST_REG 0x0014 // TSC_MTSCCNTCV1_0
#define TSC1_FIRST_REG 0x0100 // TSC_STSCCR_0
#define TSC1_LAST_REG 0x0118 // TSC_CLK_OVR_ON_0

// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARTSC_H_INC_
