//
// Copyright (c) 2018 NVIDIA Corporation.
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// Redistributions of source code must retain the above copyright notice,
// this list of conditions and the following disclaimer.
//
// Redistributions in binary form must reproduce the above copyright notice,
// this list of conditions and the following disclaimer in the documentation
// and/or other materials provided with the distribution.
//
// Neither the name of the NVIDIA Corporation nor the names of its contributors
// may be used to endorse or promote products derived from this software
// without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
// AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
// IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
// ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
// LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
// CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
// SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
// CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
// ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//

//
// DO NOT EDIT - generated by simspec!
//

#ifndef ___ARHOST1X_UCLASS_H_INC_
#define ___ARHOST1X_UCLASS_H_INC_
#define NV_MOBILE_ARHOST1X_UCLASS_H_UNIT_OF_OFFSET 1B


// Register NV_CLASS_HOST_INCR_SYNCPT_0
#define NV_CLASS_HOST_INCR_SYNCPT_0                     _MK_ADDR_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_SECURE                      0x0
#define NV_CLASS_HOST_INCR_SYNCPT_0_DUAL                        0x0
#define NV_CLASS_HOST_INCR_SYNCPT_0_SCR                         0
#define NV_CLASS_HOST_INCR_SYNCPT_0_WORD_COUNT                  0x1
#define NV_CLASS_HOST_INCR_SYNCPT_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_RESET_MASK                  _MK_MASK_CONST(0x3ffff)
#define NV_CLASS_HOST_INCR_SYNCPT_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_READ_MASK                   _MK_MASK_CONST(0x3ffff)
#define NV_CLASS_HOST_INCR_SYNCPT_0_WRITE_MASK                  _MK_MASK_CONST(0x3ffff)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_SHIFT                  _MK_SHIFT_CONST(10)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_FIELD                  _MK_FIELD_CONST(0xff, NV_CLASS_HOST_INCR_SYNCPT_0_COND_SHIFT)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_RANGE                  17:10
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_WOFFSET                        0x0
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_DEFAULT_MASK                   _MK_MASK_CONST(0xff)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_PARITY_PROTECTION                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_PLATFORM_DEPENDENT                     _MK_MASK_CONST(0x1)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_IMMEDIATE                      _MK_ENUM_CONST(0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_OP_DONE                        _MK_ENUM_CONST(1)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_RD_DONE                        _MK_ENUM_CONST(2)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_REG_WR_SAFE                    _MK_ENUM_CONST(3)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_ENGINE_IDLE                    _MK_ENUM_CONST(4)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_5                 _MK_ENUM_CONST(5)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_6                 _MK_ENUM_CONST(6)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_7                 _MK_ENUM_CONST(7)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_8                 _MK_ENUM_CONST(8)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_9                 _MK_ENUM_CONST(9)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_10                        _MK_ENUM_CONST(10)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_11                        _MK_ENUM_CONST(11)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_12                        _MK_ENUM_CONST(12)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_13                        _MK_ENUM_CONST(13)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_14                        _MK_ENUM_CONST(14)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_15                        _MK_ENUM_CONST(15)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_16                        _MK_ENUM_CONST(16)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_17                        _MK_ENUM_CONST(17)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_18                        _MK_ENUM_CONST(18)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_19                        _MK_ENUM_CONST(19)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_20                        _MK_ENUM_CONST(20)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_21                        _MK_ENUM_CONST(21)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_22                        _MK_ENUM_CONST(22)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_23                        _MK_ENUM_CONST(23)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_24                        _MK_ENUM_CONST(24)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_25                        _MK_ENUM_CONST(25)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_26                        _MK_ENUM_CONST(26)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_27                        _MK_ENUM_CONST(27)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_28                        _MK_ENUM_CONST(28)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_29                        _MK_ENUM_CONST(29)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_30                        _MK_ENUM_CONST(30)
#define NV_CLASS_HOST_INCR_SYNCPT_0_COND_COND_31                        _MK_ENUM_CONST(31)

#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_SHIFT                  _MK_SHIFT_CONST(0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_FIELD                  _MK_FIELD_CONST(0x3ff, NV_CLASS_HOST_INCR_SYNCPT_0_INDX_SHIFT)
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_RANGE                  9:0
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_WOFFSET                        0x0
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_DEFAULT_MASK                   _MK_MASK_CONST(0x3ff)
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_PARITY_PROTECTION                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_0_INDX_PLATFORM_DEPENDENT                     _MK_MASK_CONST(0x1)


// Register NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0                       _MK_ADDR_CONST(0x1)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_SECURE                        0x0
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_DUAL                  0x0
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_SCR                   0
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_WORD_COUNT                    0x1
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_RESET_MASK                    _MK_MASK_CONST(0x101)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_READ_MASK                     _MK_MASK_CONST(0x101)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_WRITE_MASK                    _MK_MASK_CONST(0x101)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_SHIFT                    _MK_SHIFT_CONST(8)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_FIELD                    _MK_FIELD_CONST(0x1, NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_SHIFT)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_RANGE                    8:8
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_WOFFSET                  0x0
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_DEFAULT                  _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_DEFAULT_MASK                     _MK_MASK_CONST(0x1)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_SW_DEFAULT                       _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_PARITY_PROTECTION                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_NO_STALL_PLATFORM_DEPENDENT                       _MK_MASK_CONST(0x1)

#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_SHIFT                  _MK_SHIFT_CONST(0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_FIELD                  _MK_FIELD_CONST(0x1, NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_SHIFT)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_RANGE                  0:0
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_WOFFSET                        0x0
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_DEFAULT_MASK                   _MK_MASK_CONST(0x1)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_PARITY_PROTECTION                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0_INCR_SYNCPT_SOFT_RESET_PLATFORM_DEPENDENT                     _MK_MASK_CONST(0x1)


// Register NV_CLASS_HOST_INCR_SYNCPT_ERROR_0
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0                       _MK_ADDR_CONST(0x2)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_SECURE                        0x0
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_DUAL                  0x0
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_SCR                   0
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_WORD_COUNT                    0x1
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_RESET_VAL                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_RESET_MASK                    _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_SW_DEFAULT_VAL                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_SW_DEFAULT_MASK                       _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_READ_MASK                     _MK_MASK_CONST(0xffffffff)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_WRITE_MASK                    _MK_MASK_CONST(0xffffffff)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_SHIFT                     _MK_SHIFT_CONST(0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_FIELD                     _MK_FIELD_CONST(0xffffffff, NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_SHIFT)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_RANGE                     31:0
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_WOFFSET                   0x0
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_DEFAULT                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_PARITY_PROTECTION                 _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_INCR_SYNCPT_ERROR_0_COND_STATUS_PLATFORM_DEPENDENT                        _MK_MASK_CONST(0x1)


// Reserved address 0x3

// Reserved address 0x4

// Reserved address 0x5

// Reserved address 0x6

// Reserved address 0x7

// Register NV_CLASS_HOST_WAIT_SYNCPT_0
#define NV_CLASS_HOST_WAIT_SYNCPT_0                     _MK_ADDR_CONST(0x8)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_SECURE                      0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_0_DUAL                        0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_0_SCR                         0
#define NV_CLASS_HOST_WAIT_SYNCPT_0_WORD_COUNT                  0x1
#define NV_CLASS_HOST_WAIT_SYNCPT_0_RESET_VAL                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_RESET_MASK                  _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_SW_DEFAULT_VAL                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_READ_MASK                   _MK_MASK_CONST(0xffffffff)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_WRITE_MASK                  _MK_MASK_CONST(0xffffffff)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_SHIFT                  _MK_SHIFT_CONST(24)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_FIELD                  _MK_FIELD_CONST(0xff, NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_SHIFT)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_RANGE                  31:24
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_WOFFSET                        0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_PARITY_PROTECTION                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_INDX_PLATFORM_DEPENDENT                     _MK_MASK_CONST(0x1)

#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_SHIFT                        _MK_SHIFT_CONST(0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_FIELD                        _MK_FIELD_CONST(0xffffff, NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_SHIFT)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_RANGE                        23:0
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_WOFFSET                      0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_DEFAULT                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_DEFAULT_MASK                 _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_SW_DEFAULT                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_PARITY_PROTECTION                    _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_0_THRESH_PLATFORM_DEPENDENT                   _MK_MASK_CONST(0x1)


// Reserved address 0x9

// Register NV_CLASS_HOST_WAIT_SYNCPT_INCR_0
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0                        _MK_ADDR_CONST(0xa)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_SECURE                         0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_DUAL                   0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_SCR                    0
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_WORD_COUNT                     0x1
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_RESET_VAL                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_RESET_MASK                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_SW_DEFAULT_VAL                         _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_READ_MASK                      _MK_MASK_CONST(0xffc00000)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_WRITE_MASK                     _MK_MASK_CONST(0xffc00000)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_SHIFT                     _MK_SHIFT_CONST(22)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_FIELD                     _MK_FIELD_CONST(0x3ff, NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_SHIFT)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_RANGE                     31:22
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_WOFFSET                   0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_DEFAULT                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_PARITY_PROTECTION                 _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_INCR_0_INDX_PLATFORM_DEPENDENT                        _MK_MASK_CONST(0x1)


// Reserved address 0xb

// Reserved address 0xc

// Reserved address 0xd

// Reserved address 0xe

// Reserved address 0xf

// Register NV_CLASS_HOST_DELAY_USEC_0
#define NV_CLASS_HOST_DELAY_USEC_0                      _MK_ADDR_CONST(0x10)
#define NV_CLASS_HOST_DELAY_USEC_0_SECURE                       0x0
#define NV_CLASS_HOST_DELAY_USEC_0_DUAL                         0x0
#define NV_CLASS_HOST_DELAY_USEC_0_SCR                  0
#define NV_CLASS_HOST_DELAY_USEC_0_WORD_COUNT                   0x1
#define NV_CLASS_HOST_DELAY_USEC_0_RESET_VAL                    _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_RESET_MASK                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_SW_DEFAULT_VAL                       _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_SW_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_READ_MASK                    _MK_MASK_CONST(0xfffff)
#define NV_CLASS_HOST_DELAY_USEC_0_WRITE_MASK                   _MK_MASK_CONST(0xfffff)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_SHIFT                  _MK_SHIFT_CONST(0)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_FIELD                  _MK_FIELD_CONST(0xfffff, NV_CLASS_HOST_DELAY_USEC_0_NUSEC_SHIFT)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_RANGE                  19:0
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_WOFFSET                        0x0
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_SW_DEFAULT                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_SW_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_PARITY_PROTECTION                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_DELAY_USEC_0_NUSEC_PLATFORM_DEPENDENT                     _MK_MASK_CONST(0x1)


// Reserved address 0x11

// Reserved address 0x12

// Reserved address 0x13

// Reserved address 0x14

// Reserved address 0x15

// Reserved address 0x16

// Reserved address 0x17

// Reserved address 0x18

// Reserved address 0x19

// Reserved address 0x1a

// Reserved address 0x1b

// Reserved address 0x1c

// Reserved address 0x1d

// Reserved address 0x1e

// Reserved address 0x1f

// Reserved address 0x20

// Reserved address 0x21

// Reserved address 0x22

// Reserved address 0x23

// Reserved address 0x24

// Reserved address 0x25

// Reserved address 0x26

// Reserved address 0x27

// Reserved address 0x28

// Reserved address 0x29

// Reserved address 0x2a

// Reserved address 0x2b

// Reserved address 0x2c

// Reserved address 0x2d

// Reserved address 0x2e

// Reserved address 0x2f

// Reserved address 0x30

// Reserved address 0x31

// Reserved address 0x32

// Reserved address 0x33

// Reserved address 0x34

// Reserved address 0x35

// Reserved address 0x36

// Reserved address 0x37

// Reserved address 0x38

// Reserved address 0x39

// Reserved address 0x3a

// Reserved address 0x3b

// Reserved address 0x3c

// Reserved address 0x3d

// Reserved address 0x3e

// Reserved address 0x3f

// Reserved address 0x40

// Reserved address 0x41

// Reserved address 0x42

// Reserved address 0x43

// Reserved address 0x44

// Reserved address 0x45

// Reserved address 0x46

// Reserved address 0x47

// Reserved address 0x48

// Reserved address 0x49

// Reserved address 0x4a

// Reserved address 0x4b

// Reserved address 0x4c

// Reserved address 0x4d

// Register NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0                  _MK_ADDR_CONST(0x4e)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_SECURE                   0x0
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_DUAL                     0x0
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_SCR                      0
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_WORD_COUNT                       0x1
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_RESET_MASK                       _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_READ_MASK                        _MK_MASK_CONST(0xffffffff)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_WRITE_MASK                       _MK_MASK_CONST(0xffffffff)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_SHIFT                     _MK_SHIFT_CONST(0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_FIELD                     _MK_FIELD_CONST(0xffffffff, NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_SHIFT)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_RANGE                     31:0
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_WOFFSET                   0x0
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_DEFAULT                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_DEFAULT_MASK                      _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_SW_DEFAULT                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_SW_DEFAULT_MASK                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_PARITY_PROTECTION                 _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0_CHANNEL_SYNCPT_PAYLOAD_PLATFORM_DEPENDENT                        _MK_MASK_CONST(0x1)


// Reserved address 0x4f

// Register NV_CLASS_HOST_WAIT_SYNCPT_32_0
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0                  _MK_ADDR_CONST(0x50)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_SECURE                   0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_DUAL                     0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_SCR                      0
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_WORD_COUNT                       0x1
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_RESET_VAL                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_RESET_MASK                       _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_SW_DEFAULT_VAL                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_SW_DEFAULT_MASK                  _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_READ_MASK                        _MK_MASK_CONST(0x3ff)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_WRITE_MASK                       _MK_MASK_CONST(0x3ff)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_SHIFT                       _MK_SHIFT_CONST(0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_FIELD                       _MK_FIELD_CONST(0x3ff, NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_SHIFT)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_RANGE                       9:0
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_WOFFSET                     0x0
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_DEFAULT                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_DEFAULT_MASK                        _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_SW_DEFAULT                  _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_SW_DEFAULT_MASK                     _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_PARITY_PROTECTION                   _MK_MASK_CONST(0x0)
#define NV_CLASS_HOST_WAIT_SYNCPT_32_0_INDX_PLATFORM_DEPENDENT                  _MK_MASK_CONST(0x1)


//
// REGISTER LIST
//
#define LIST_ARHOST1X_UCLASS_REGS(_op_) \
_op_(NV_CLASS_HOST_INCR_SYNCPT_0) \
_op_(NV_CLASS_HOST_INCR_SYNCPT_CNTRL_0) \
_op_(NV_CLASS_HOST_INCR_SYNCPT_ERROR_0) \
_op_(NV_CLASS_HOST_WAIT_SYNCPT_0) \
_op_(NV_CLASS_HOST_WAIT_SYNCPT_INCR_0) \
_op_(NV_CLASS_HOST_DELAY_USEC_0) \
_op_(NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0) \
_op_(NV_CLASS_HOST_WAIT_SYNCPT_32_0)


//
// ADDRESS SPACES
//

#define BASE_ADDRESS_NV_CLASS_HOST      0x00000000

//
// ARHOST1X_UCLASS REGISTER BANKS
//

#define NV_CLASS_HOST0_FIRST_REG 0x0000 // NV_CLASS_HOST_INCR_SYNCPT_0
#define NV_CLASS_HOST0_LAST_REG 0x0002 // NV_CLASS_HOST_INCR_SYNCPT_ERROR_0
#define NV_CLASS_HOST1_FIRST_REG 0x0008 // NV_CLASS_HOST_WAIT_SYNCPT_0
#define NV_CLASS_HOST1_LAST_REG 0x0008 // NV_CLASS_HOST_WAIT_SYNCPT_0
#define NV_CLASS_HOST2_FIRST_REG 0x000a // NV_CLASS_HOST_WAIT_SYNCPT_INCR_0
#define NV_CLASS_HOST2_LAST_REG 0x000a // NV_CLASS_HOST_WAIT_SYNCPT_INCR_0
#define NV_CLASS_HOST3_FIRST_REG 0x0010 // NV_CLASS_HOST_DELAY_USEC_0
#define NV_CLASS_HOST3_LAST_REG 0x0010 // NV_CLASS_HOST_DELAY_USEC_0
#define NV_CLASS_HOST4_FIRST_REG 0x004e // NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0
#define NV_CLASS_HOST4_LAST_REG 0x004e // NV_CLASS_HOST_LOAD_SYNCPT_PAYLOAD_32_0
#define NV_CLASS_HOST5_FIRST_REG 0x0050 // NV_CLASS_HOST_WAIT_SYNCPT_32_0
#define NV_CLASS_HOST5_LAST_REG 0x0050 // NV_CLASS_HOST_WAIT_SYNCPT_32_0

// To satisfy various compilers and platforms,
// we let users control the types and syntax of certain constants, using macros.
#ifndef _MK_SHIFT_CONST
  #define _MK_SHIFT_CONST(_constant_) _constant_
#endif
#ifndef _MK_MASK_CONST
  #define _MK_MASK_CONST(_constant_) _constant_
#endif
#ifndef _MK_ENUM_CONST
  #define _MK_ENUM_CONST(_constant_) (_constant_ ## UL)
#endif
#ifndef _MK_ADDR_CONST
  #define _MK_ADDR_CONST(_constant_) _constant_
#endif
#ifndef _MK_FIELD_CONST
  #define _MK_FIELD_CONST(_mask_, _shift_) (_MK_MASK_CONST(_mask_) << _MK_SHIFT_CONST(_shift_))
#endif

#endif // ifndef ___ARHOST1X_UCLASS_H_INC_
